// AUTO-GENERATED by scripts/import-wger.js — do not edit by hand.
// Source: wger.de exercise database (CC-BY-SA 4.0)
// Re-run with: npm run import:exercises
// Last imported: 2026-05-03T07:05:23.744Z
// Exercise count: 263

export const ALL_EXERCISES = [
  {
    "id": "1-ARM HALF-KNEELING LAT PULLDOWN",
    "label": "1-ARM HALF-KNEELING LAT PULLDOWN",
    "muscles": [
      "back",
      "biceps"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "biceps"
    ]
  },
  {
    "id": "AB WHEEL",
    "label": "AB WHEEL",
    "muscles": [
      "abs"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "ABDOMINAL CRUNCH",
    "label": "ABDOMINAL CRUNCH",
    "muscles": [
      "abs"
    ],
    "equipment": "bodyweight",
    "aliases": [],
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": [],
    "bw_coefficient": 0.35
  },
  {
    "id": "ALTERNATING BICEPS CURLS WITH DUMBBELL",
    "label": "ALTERNATING BICEPS CURLS WITH DUMBBELL",
    "muscles": [
      "biceps"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "biceps"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "ALTERNATING DUMBBELL HAMMER CURL",
    "label": "ALTERNATING DUMBBELL HAMMER CURL",
    "muscles": [
      "biceps",
      "forearms"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "biceps"
    ],
    "secondaryMuscles": [
      "forearms"
    ]
  },
  {
    "id": "ALTERNATING HIGH CABLE ROW",
    "label": "ALTERNATING HIGH CABLE ROW",
    "muscles": [
      "back",
      "biceps"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "biceps"
    ]
  },
  {
    "id": "ARM RAISES (T/Y/I)",
    "label": "ARM RAISES (T/Y/I)",
    "muscles": [
      "shoulders",
      "back"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "shoulders"
    ],
    "secondaryMuscles": [
      "back"
    ]
  },
  {
    "id": "ASSISTED PULL-UP",
    "label": "ASSISTED PULL-UP",
    "muscles": [
      "back",
      "biceps"
    ],
    "equipment": "bodyweight",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "biceps"
    ],
    "bw_coefficient": 0.5
  },
  {
    "id": "BARBELL AB ROLLOUT",
    "label": "BARBELL AB ROLLOUT",
    "muscles": [
      "abs"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "BARBELL HIP THRUST",
    "label": "BARBELL HIP THRUST",
    "muscles": [
      "glutes",
      "hamstrings"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "glutes"
    ],
    "secondaryMuscles": [
      "hamstrings"
    ],
    "is_isolation_override": true
  },
  {
    "id": "BARBELL LUNGES STANDING",
    "label": "BARBELL LUNGES STANDING",
    "muscles": [
      "quads",
      "glutes"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "quads"
    ],
    "secondaryMuscles": [
      "glutes"
    ]
  },
  {
    "id": "BARBELL ROMANIAN DEADLIFT (RDL)",
    "label": "BARBELL ROMANIAN DEADLIFT (RDL)",
    "muscles": [
      "hamstrings",
      "glutes",
      "back",
      "abs"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "hamstrings"
    ],
    "secondaryMuscles": [
      "glutes",
      "back",
      "abs"
    ],
    "is_king_compound": true
  },
  {
    "id": "BARBELL ROW (OVERHAND)",
    "label": "BARBELL ROW (OVERHAND)",
    "muscles": [
      "back",
      "biceps"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "biceps"
    ]
  },
  {
    "id": "BARBELL ROW (UNDERHAND)",
    "label": "BARBELL ROW (UNDERHAND)",
    "muscles": [
      "back",
      "biceps"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "biceps"
    ]
  },
  {
    "id": "BARBELL SQUAT",
    "label": "BARBELL SQUAT",
    "muscles": [
      "quads",
      "glutes",
      "back"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "quads"
    ],
    "secondaryMuscles": [
      "glutes",
      "back"
    ],
    "is_king_compound": true
  },
  {
    "id": "BARBELL STEP BACK LUNGE",
    "label": "BARBELL STEP BACK LUNGE",
    "muscles": [
      "quads",
      "glutes"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "quads"
    ],
    "secondaryMuscles": [
      "glutes"
    ]
  },
  {
    "id": "BARBELL TRICEPS EXTENSION",
    "label": "BARBELL TRICEPS EXTENSION",
    "muscles": [
      "triceps"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "triceps"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "BARBELL WRIST CURL",
    "label": "BARBELL WRIST CURL",
    "muscles": [
      "forearms"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "forearms"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "BAYESIAN CURL",
    "label": "BAYESIAN CURL",
    "muscles": [
      "biceps"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "biceps"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "BEHIND THE BACK CABLE LATERAL RAISE",
    "label": "BEHIND THE BACK CABLE LATERAL RAISE",
    "muscles": [
      "shoulders"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "shoulders"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "BELT SQUAT",
    "label": "BELT SQUAT",
    "muscles": [
      "quads",
      "glutes",
      "hamstrings"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "quads"
    ],
    "secondaryMuscles": [
      "glutes",
      "hamstrings"
    ],
    "is_king_compound": true
  },
  {
    "id": "BENCH PRESS",
    "label": "BENCH PRESS",
    "muscles": [
      "chest",
      "shoulders",
      "triceps"
    ],
    "equipment": "barbell",
    "aliases": [
      "BP",
      "BENCH"
    ],
    "primaryMuscles": [
      "chest"
    ],
    "secondaryMuscles": [
      "shoulders",
      "triceps"
    ]
  },
  {
    "id": "BICEPS CURL MACHINE",
    "label": "BICEPS CURL MACHINE",
    "muscles": [
      "biceps"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "biceps"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "BICEPS CURLS WITH BARBELL",
    "label": "BICEPS CURLS WITH BARBELL",
    "muscles": [
      "biceps"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "biceps"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "BICEPS CURLS WITH SZ-BAR",
    "label": "BICEPS CURLS WITH SZ-BAR",
    "muscles": [
      "biceps"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "biceps"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "BICYCLE CRUNCHES",
    "label": "BICYCLE CRUNCHES",
    "muscles": [
      "abs"
    ],
    "equipment": "bodyweight",
    "aliases": [],
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": [],
    "bw_coefficient": 0.35
  },
  {
    "id": "BODYWEIGHT BICEPS CURL",
    "label": "BODYWEIGHT BICEPS CURL",
    "muscles": [
      "biceps"
    ],
    "equipment": "bodyweight",
    "aliases": [],
    "primaryMuscles": [
      "biceps"
    ],
    "secondaryMuscles": [],
    "bw_coefficient": 0.7
  },
  {
    "id": "BOX SQUAT",
    "label": "BOX SQUAT",
    "muscles": [
      "quads",
      "glutes",
      "back"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "quads"
    ],
    "secondaryMuscles": [
      "glutes",
      "back"
    ],
    "is_king_compound": true
  },
  {
    "id": "BULGARIAN SQUAT WITH DUMBBELLS",
    "label": "BULGARIAN SQUAT WITH DUMBBELLS",
    "muscles": [
      "quads",
      "glutes"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "quads"
    ],
    "secondaryMuscles": [
      "glutes"
    ]
  },
  {
    "id": "BUTTERFLY",
    "label": "BUTTERFLY",
    "muscles": [
      "chest"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "chest"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "BUTTERFLY NARROW GRIP",
    "label": "BUTTERFLY NARROW GRIP",
    "muscles": [
      "chest"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "chest"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "BUTTERFLY REVERSE",
    "label": "BUTTERFLY REVERSE",
    "muscles": [
      "shoulders",
      "back"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "shoulders"
    ],
    "secondaryMuscles": [
      "back"
    ],
    "is_isolation_override": true
  },
  {
    "id": "CABLE CHEST PRESS - DECLINE",
    "label": "CABLE CHEST PRESS - DECLINE",
    "muscles": [
      "chest",
      "shoulders",
      "triceps"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "chest"
    ],
    "secondaryMuscles": [
      "shoulders",
      "triceps"
    ]
  },
  {
    "id": "CABLE CHEST PRESS - INCLINE",
    "label": "CABLE CHEST PRESS - INCLINE",
    "muscles": [
      "chest",
      "shoulders",
      "triceps"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "chest"
    ],
    "secondaryMuscles": [
      "shoulders",
      "triceps"
    ]
  },
  {
    "id": "CABLE CONCENTRATION CURL",
    "label": "CABLE CONCENTRATION CURL",
    "muscles": [
      "biceps"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "biceps"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "CABLE CROSS-OVER",
    "label": "CABLE CROSS-OVER",
    "muscles": [
      "chest",
      "shoulders"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "chest"
    ],
    "secondaryMuscles": [
      "shoulders"
    ]
  },
  {
    "id": "CABLE CURLS",
    "label": "CABLE CURLS",
    "muscles": [
      "biceps"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "biceps"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "CABLE EXTERNAL ROTATION",
    "label": "CABLE EXTERNAL ROTATION",
    "muscles": [
      "shoulders"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "shoulders"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "CABLE FLY",
    "label": "CABLE FLY",
    "muscles": [
      "chest",
      "shoulders"
    ],
    "equipment": "cable",
    "aliases": [
      "CF"
    ],
    "primaryMuscles": [
      "chest"
    ],
    "secondaryMuscles": [
      "shoulders"
    ]
  },
  {
    "id": "CABLE FLY LOWER CHEST",
    "label": "CABLE FLY LOWER CHEST",
    "muscles": [
      "chest",
      "shoulders"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "chest"
    ],
    "secondaryMuscles": [
      "shoulders"
    ]
  },
  {
    "id": "CABLE FLY UPPER CHEST",
    "label": "CABLE FLY UPPER CHEST",
    "muscles": [
      "chest",
      "shoulders"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "chest"
    ],
    "secondaryMuscles": [
      "shoulders"
    ]
  },
  {
    "id": "CABLE LATERAL RAISES (SINGLE ARM)",
    "label": "CABLE LATERAL RAISES (SINGLE ARM)",
    "muscles": [
      "shoulders"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "shoulders"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "CABLE PRESS AROUND",
    "label": "CABLE PRESS AROUND",
    "muscles": [
      "chest",
      "shoulders"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "chest"
    ],
    "secondaryMuscles": [
      "shoulders"
    ]
  },
  {
    "id": "CABLE PULL THROUGH",
    "label": "CABLE PULL THROUGH",
    "muscles": [
      "glutes",
      "hamstrings"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "glutes"
    ],
    "secondaryMuscles": [
      "hamstrings"
    ],
    "is_isolation_override": true
  },
  {
    "id": "CABLE REAR DELT FLY",
    "label": "CABLE REAR DELT FLY",
    "muscles": [
      "shoulders",
      "back"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "shoulders"
    ],
    "secondaryMuscles": [
      "back"
    ],
    "is_isolation_override": true
  },
  {
    "id": "CABLE SHRUG-IN",
    "label": "CABLE SHRUG-IN",
    "muscles": [
      "back"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "CABLE TRI EXTENSION - EXTERNAL ROTATION",
    "label": "CABLE TRI EXTENSION - EXTERNAL ROTATION",
    "muscles": [
      "triceps"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "triceps"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "CABLE TRI EXTENSION - INTERNAL ROTATION",
    "label": "CABLE TRI EXTENSION - INTERNAL ROTATION",
    "muscles": [
      "triceps"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "triceps"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "CABLE TRICEP KICKBACK",
    "label": "CABLE TRICEP KICKBACK",
    "muscles": [
      "triceps"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "triceps"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "CABLE TRICEPS PRESS",
    "label": "CABLE TRICEPS PRESS",
    "muscles": [
      "triceps"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "triceps"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "CABLE WOODCHOPPERS",
    "label": "CABLE WOODCHOPPERS",
    "muscles": [
      "abs"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "CALF PRESS USING LEG PRESS MACHINE",
    "label": "CALF PRESS USING LEG PRESS MACHINE",
    "muscles": [
      "calves"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "calves"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "CALF RAISES, ONE LEGGED",
    "label": "CALF RAISES, ONE LEGGED",
    "muscles": [
      "calves"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "calves"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "CHEST-SUPPORTED REAR DELT RAISE",
    "label": "CHEST-SUPPORTED REAR DELT RAISE",
    "muscles": [
      "shoulders",
      "back"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "shoulders"
    ],
    "secondaryMuscles": [
      "back"
    ],
    "is_isolation_override": true
  },
  {
    "id": "CHIN-UPS",
    "label": "CHIN-UPS",
    "muscles": [
      "back",
      "biceps"
    ],
    "equipment": "bodyweight",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "biceps"
    ],
    "bw_coefficient": 1.0
  },
  {
    "id": "CLOSE-GRIP BENCH PRESS",
    "label": "CLOSE-GRIP BENCH PRESS",
    "muscles": [
      "triceps",
      "chest",
      "shoulders"
    ],
    "equipment": "barbell",
    "aliases": [
      "CGBP"
    ],
    "primaryMuscles": [
      "triceps"
    ],
    "secondaryMuscles": [
      "chest",
      "shoulders"
    ]
  },
  {
    "id": "CLOSE-GRIP LAT PULL DOWN",
    "label": "CLOSE-GRIP LAT PULL DOWN",
    "muscles": [
      "back",
      "biceps"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "biceps"
    ]
  },
  {
    "id": "CLOSE-GRIP PRESS-UPS",
    "label": "CLOSE-GRIP PRESS-UPS",
    "muscles": [
      "triceps",
      "chest",
      "shoulders"
    ],
    "equipment": "bodyweight",
    "aliases": [],
    "primaryMuscles": [
      "triceps"
    ],
    "secondaryMuscles": [
      "chest",
      "shoulders"
    ],
    "bw_coefficient": 0.65
  },
  {
    "id": "CROSS-BENCH DUMBBELL PULLOVERS",
    "label": "CROSS-BENCH DUMBBELL PULLOVERS",
    "muscles": [
      "back",
      "chest"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "chest"
    ]
  },
  {
    "id": "CROSS-BODY CABLE Y-RAISE",
    "label": "CROSS-BODY CABLE Y-RAISE",
    "muscles": [
      "shoulders",
      "back"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "shoulders"
    ],
    "secondaryMuscles": [
      "back"
    ]
  },
  {
    "id": "CRUNCHES ON MACHINE",
    "label": "CRUNCHES ON MACHINE",
    "muscles": [
      "abs"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "CRUNCHES WITH CABLE",
    "label": "CRUNCHES WITH CABLE",
    "muscles": [
      "abs"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "CRUNCHES WITH LEGS UP",
    "label": "CRUNCHES WITH LEGS UP",
    "muscles": [
      "abs"
    ],
    "equipment": "bodyweight",
    "aliases": [],
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": [],
    "bw_coefficient": 0.35
  },
  {
    "id": "DB CROSS BODY HAMMER CURLS",
    "label": "DB CROSS BODY HAMMER CURLS",
    "muscles": [
      "biceps",
      "forearms"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "biceps"
    ],
    "secondaryMuscles": [
      "forearms"
    ]
  },
  {
    "id": "DB SKULL CRUSHERS",
    "label": "DB SKULL CRUSHERS",
    "muscles": [
      "triceps"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "triceps"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "DEADLIFTS",
    "label": "DEADLIFTS",
    "muscles": [
      "back",
      "glutes",
      "hamstrings",
      "quads"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "glutes",
      "hamstrings",
      "quads"
    ],
    "is_king_compound": true
  },
  {
    "id": "DECLINE BENCH LEG RAISE",
    "label": "DECLINE BENCH LEG RAISE",
    "muscles": [
      "abs"
    ],
    "equipment": "bodyweight",
    "aliases": [],
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": [],
    "bw_coefficient": 0.35
  },
  {
    "id": "DECLINE BENCH PRESS BARBELL",
    "label": "DECLINE BENCH PRESS BARBELL",
    "muscles": [
      "chest",
      "shoulders",
      "triceps"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "chest"
    ],
    "secondaryMuscles": [
      "shoulders",
      "triceps"
    ]
  },
  {
    "id": "DECLINE BENCH PRESS DUMBBELL",
    "label": "DECLINE BENCH PRESS DUMBBELL",
    "muscles": [
      "chest",
      "shoulders",
      "triceps"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "chest"
    ],
    "secondaryMuscles": [
      "shoulders",
      "triceps"
    ]
  },
  {
    "id": "DECLINE PUSHUPS",
    "label": "DECLINE PUSHUPS",
    "muscles": [
      "chest",
      "shoulders",
      "triceps"
    ],
    "equipment": "bodyweight",
    "aliases": [],
    "primaryMuscles": [
      "chest"
    ],
    "secondaryMuscles": [
      "shoulders",
      "triceps"
    ],
    "bw_coefficient": 0.75
  },
  {
    "id": "DEFICIT DEADLIFT",
    "label": "DEFICIT DEADLIFT",
    "muscles": [
      "back",
      "glutes",
      "hamstrings",
      "quads"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "glutes",
      "hamstrings",
      "quads"
    ],
    "is_king_compound": true
  },
  {
    "id": "DEFICIT PUSH UPS",
    "label": "DEFICIT PUSH UPS",
    "muscles": [
      "chest",
      "shoulders",
      "triceps"
    ],
    "equipment": "bodyweight",
    "aliases": [],
    "primaryMuscles": [
      "chest"
    ],
    "secondaryMuscles": [
      "shoulders",
      "triceps"
    ],
    "bw_coefficient": 0.65
  },
  {
    "id": "DIAMOND PUSH UPS",
    "label": "DIAMOND PUSH UPS",
    "muscles": [
      "triceps",
      "chest",
      "shoulders"
    ],
    "equipment": "bodyweight",
    "aliases": [],
    "primaryMuscles": [
      "triceps"
    ],
    "secondaryMuscles": [
      "chest",
      "shoulders"
    ],
    "bw_coefficient": 0.65
  },
  {
    "id": "DIPS",
    "label": "DIPS",
    "muscles": [
      "chest",
      "triceps"
    ],
    "equipment": "bodyweight",
    "aliases": [],
    "primaryMuscles": [
      "chest"
    ],
    "secondaryMuscles": [
      "triceps"
    ],
    "bw_coefficient": 1.0
  },
  {
    "id": "DIPS BETWEEN TWO BENCHES",
    "label": "DIPS BETWEEN TWO BENCHES",
    "muscles": [
      "chest",
      "triceps"
    ],
    "equipment": "bodyweight",
    "aliases": [],
    "primaryMuscles": [
      "chest"
    ],
    "secondaryMuscles": [
      "triceps"
    ],
    "bw_coefficient": 0.5
  },
  {
    "id": "DOUBLE LEG CALF RAISE",
    "label": "DOUBLE LEG CALF RAISE",
    "muscles": [
      "calves"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "calves"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "DRAG PUSHDOWN",
    "label": "DRAG PUSHDOWN",
    "muscles": [
      "triceps"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "triceps"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "DUMBBELL BENCH PRESS",
    "label": "DUMBBELL BENCH PRESS",
    "muscles": [
      "chest",
      "shoulders",
      "triceps"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "chest"
    ],
    "secondaryMuscles": [
      "shoulders",
      "triceps"
    ]
  },
  {
    "id": "DUMBBELL BENT OVER FACE PULL",
    "label": "DUMBBELL BENT OVER FACE PULL",
    "muscles": [
      "back",
      "shoulders"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "shoulders"
    ]
  },
  {
    "id": "DUMBBELL BENT OVER ROW",
    "label": "DUMBBELL BENT OVER ROW",
    "muscles": [
      "back",
      "biceps"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "biceps"
    ]
  },
  {
    "id": "DUMBBELL CLOSE GRIP BENCH PRESS",
    "label": "DUMBBELL CLOSE GRIP BENCH PRESS",
    "muscles": [
      "triceps",
      "chest",
      "shoulders"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "triceps"
    ],
    "secondaryMuscles": [
      "chest",
      "shoulders"
    ]
  },
  {
    "id": "DUMBBELL CONCENTRATION CURL",
    "label": "DUMBBELL CONCENTRATION CURL",
    "muscles": [
      "biceps"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "biceps"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "DUMBBELL CRUNCHES",
    "label": "DUMBBELL CRUNCHES",
    "muscles": [
      "abs"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "DUMBBELL CURL",
    "label": "DUMBBELL CURL",
    "muscles": [
      "biceps"
    ],
    "equipment": "dumbbell",
    "aliases": [
      "DBC"
    ],
    "primaryMuscles": [
      "biceps"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "DUMBBELL FRONT SQUAT",
    "label": "DUMBBELL FRONT SQUAT",
    "muscles": [
      "quads",
      "glutes"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "quads"
    ],
    "secondaryMuscles": [
      "glutes"
    ]
  },
  {
    "id": "DUMBBELL GOBLET SQUAT",
    "label": "DUMBBELL GOBLET SQUAT",
    "muscles": [
      "quads",
      "glutes"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "quads"
    ],
    "secondaryMuscles": [
      "glutes"
    ]
  },
  {
    "id": "DUMBBELL HIP THRUST",
    "label": "DUMBBELL HIP THRUST",
    "muscles": [
      "glutes",
      "hamstrings"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "glutes"
    ],
    "secondaryMuscles": [
      "hamstrings"
    ],
    "is_isolation_override": true
  },
  {
    "id": "DUMBBELL INCLINE CURL",
    "label": "DUMBBELL INCLINE CURL",
    "muscles": [
      "biceps"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "biceps"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "DUMBBELL LUNGES STANDING",
    "label": "DUMBBELL LUNGES STANDING",
    "muscles": [
      "quads",
      "glutes"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "quads"
    ],
    "secondaryMuscles": [
      "glutes"
    ]
  },
  {
    "id": "DUMBBELL LUNGES WALKING",
    "label": "DUMBBELL LUNGES WALKING",
    "muscles": [
      "quads",
      "glutes"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "quads"
    ],
    "secondaryMuscles": [
      "glutes"
    ]
  },
  {
    "id": "DUMBBELL PULLOVER",
    "label": "DUMBBELL PULLOVER",
    "muscles": [
      "back",
      "chest"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "chest"
    ]
  },
  {
    "id": "DUMBBELL REAR DELT ROW",
    "label": "DUMBBELL REAR DELT ROW",
    "muscles": [
      "shoulders",
      "back"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "shoulders"
    ],
    "secondaryMuscles": [
      "back"
    ],
    "is_isolation_override": true
  },
  {
    "id": "DUMBBELL REAR LUNGE",
    "label": "DUMBBELL REAR LUNGE",
    "muscles": [
      "quads",
      "glutes"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "quads"
    ],
    "secondaryMuscles": [
      "glutes"
    ]
  },
  {
    "id": "DUMBBELL ROMANIAN DEADLIFT",
    "label": "DUMBBELL ROMANIAN DEADLIFT",
    "muscles": [
      "hamstrings",
      "glutes",
      "back"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "hamstrings"
    ],
    "secondaryMuscles": [
      "glutes",
      "back"
    ]
  },
  {
    "id": "DUMBBELL SCAPTION",
    "label": "DUMBBELL SCAPTION",
    "muscles": [
      "shoulders"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "shoulders"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "DUMBBELL SIDE BEND",
    "label": "DUMBBELL SIDE BEND",
    "muscles": [
      "abs"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "DUMBBELL SINGLE-LEG HIP THRUST",
    "label": "DUMBBELL SINGLE-LEG HIP THRUST",
    "muscles": [
      "glutes",
      "hamstrings"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "glutes"
    ],
    "secondaryMuscles": [
      "hamstrings"
    ],
    "is_isolation_override": true
  },
  {
    "id": "DUMBBELL THRUSTER",
    "label": "DUMBBELL THRUSTER",
    "muscles": [
      "quads",
      "shoulders",
      "glutes",
      "triceps"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "quads",
      "shoulders"
    ],
    "secondaryMuscles": [
      "glutes",
      "triceps"
    ]
  },
  {
    "id": "DUMBBELL TRICEPS EXTENSION",
    "label": "DUMBBELL TRICEPS EXTENSION",
    "muscles": [
      "triceps"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "triceps"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "DUMBBELL UPRIGHT-ROW",
    "label": "DUMBBELL UPRIGHT-ROW",
    "muscles": [
      "shoulders",
      "back"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "shoulders"
    ],
    "secondaryMuscles": [
      "back"
    ]
  },
  {
    "id": "FACEPULL",
    "label": "FACEPULL",
    "muscles": [
      "back",
      "shoulders"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "shoulders"
    ]
  },
  {
    "id": "FLOOR SKULL CRUSHER",
    "label": "FLOOR SKULL CRUSHER",
    "muscles": [
      "triceps"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "triceps"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "FLUTTER KICKS",
    "label": "FLUTTER KICKS",
    "muscles": [
      "abs"
    ],
    "equipment": "bodyweight",
    "aliases": [],
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": [],
    "bw_coefficient": 0.35
  },
  {
    "id": "FLY WITH DUMBBELLS",
    "label": "FLY WITH DUMBBELLS",
    "muscles": [
      "chest",
      "shoulders"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "chest"
    ],
    "secondaryMuscles": [
      "shoulders"
    ]
  },
  {
    "id": "FLY WITH DUMBBELLS, DECLINE BENCH",
    "label": "FLY WITH DUMBBELLS, DECLINE BENCH",
    "muscles": [
      "chest",
      "shoulders"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "chest"
    ],
    "secondaryMuscles": [
      "shoulders"
    ]
  },
  {
    "id": "FRONT PLATE RAISE",
    "label": "FRONT PLATE RAISE",
    "muscles": [
      "shoulders"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "shoulders"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "FRONT PULL NARROW",
    "label": "FRONT PULL NARROW",
    "muscles": [
      "back",
      "biceps"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "biceps"
    ]
  },
  {
    "id": "FRONT PULL WIDE",
    "label": "FRONT PULL WIDE",
    "muscles": [
      "back",
      "biceps"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "biceps"
    ]
  },
  {
    "id": "FRONT RAISE (CABLE)",
    "label": "FRONT RAISE (CABLE)",
    "muscles": [
      "shoulders"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "shoulders"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "FRONT RAISES",
    "label": "FRONT RAISES",
    "muscles": [
      "shoulders"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "shoulders"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "FRONT SQUATS",
    "label": "FRONT SQUATS",
    "muscles": [
      "quads",
      "glutes",
      "abs"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "quads"
    ],
    "secondaryMuscles": [
      "glutes",
      "abs"
    ],
    "is_king_compound": true
  },
  {
    "id": "GLUTE DRIVE",
    "label": "GLUTE DRIVE",
    "muscles": [
      "glutes",
      "hamstrings"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "glutes"
    ],
    "secondaryMuscles": [
      "hamstrings"
    ],
    "is_isolation_override": true
  },
  {
    "id": "GLUTE KICKBACK (MACHINE)",
    "label": "GLUTE KICKBACK (MACHINE)",
    "muscles": [
      "glutes",
      "hamstrings"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "glutes"
    ],
    "secondaryMuscles": [
      "hamstrings"
    ],
    "is_isolation_override": true
  },
  {
    "id": "GOOD MORNINGS",
    "label": "GOOD MORNINGS",
    "muscles": [
      "hamstrings",
      "glutes",
      "back"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "hamstrings"
    ],
    "secondaryMuscles": [
      "glutes",
      "back"
    ]
  },
  {
    "id": "HACK SQUATS",
    "label": "HACK SQUATS",
    "muscles": [
      "quads",
      "glutes",
      "hamstrings"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "quads"
    ],
    "secondaryMuscles": [
      "glutes",
      "hamstrings"
    ],
    "is_king_compound": true
  },
  {
    "id": "HAMMER CURL",
    "label": "HAMMER CURL",
    "muscles": [
      "biceps",
      "forearms"
    ],
    "equipment": "dumbbell",
    "aliases": [
      "HC"
    ],
    "primaryMuscles": [
      "biceps"
    ],
    "secondaryMuscles": [
      "forearms"
    ]
  },
  {
    "id": "HAMMERCURLS ON CABLE",
    "label": "HAMMERCURLS ON CABLE",
    "muscles": [
      "biceps",
      "forearms"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "biceps"
    ],
    "secondaryMuscles": [
      "forearms"
    ]
  },
  {
    "id": "HAMMERSTRENGTH DECLINE CHEST PRESS",
    "label": "HAMMERSTRENGTH DECLINE CHEST PRESS",
    "muscles": [
      "chest",
      "shoulders",
      "triceps"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "chest"
    ],
    "secondaryMuscles": [
      "shoulders",
      "triceps"
    ]
  },
  {
    "id": "HANGING LEG RAISES",
    "label": "HANGING LEG RAISES",
    "muscles": [
      "abs"
    ],
    "equipment": "bodyweight",
    "aliases": [],
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": [],
    "bw_coefficient": 0.5
  },
  {
    "id": "HIGH ROW",
    "label": "HIGH ROW",
    "muscles": [
      "back",
      "biceps"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "biceps"
    ]
  },
  {
    "id": "HIGH-CABLE LATERAL RAISE",
    "label": "HIGH-CABLE LATERAL RAISE",
    "muscles": [
      "shoulders"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "shoulders"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "HIGH-INCLINE SMITH MACHINE PRESS",
    "label": "HIGH-INCLINE SMITH MACHINE PRESS",
    "muscles": [
      "shoulders",
      "chest",
      "triceps"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "shoulders"
    ],
    "secondaryMuscles": [
      "chest",
      "triceps"
    ]
  },
  {
    "id": "HYPEREXTENSIONS",
    "label": "HYPEREXTENSIONS",
    "muscles": [
      "back",
      "glutes",
      "hamstrings"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "glutes",
      "hamstrings"
    ]
  },
  {
    "id": "INCLINE BENCH PRESS - BARBELL",
    "label": "INCLINE BENCH PRESS - BARBELL",
    "muscles": [
      "chest",
      "shoulders",
      "triceps"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "chest"
    ],
    "secondaryMuscles": [
      "shoulders",
      "triceps"
    ]
  },
  {
    "id": "INCLINE BENCH PRESS - DUMBBELL",
    "label": "INCLINE BENCH PRESS - DUMBBELL",
    "muscles": [
      "chest",
      "shoulders",
      "triceps"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "chest"
    ],
    "secondaryMuscles": [
      "shoulders",
      "triceps"
    ]
  },
  {
    "id": "INCLINE BENCH REVERSE FLY",
    "label": "INCLINE BENCH REVERSE FLY",
    "muscles": [
      "shoulders",
      "back"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "shoulders"
    ],
    "secondaryMuscles": [
      "back"
    ],
    "is_isolation_override": true
  },
  {
    "id": "INCLINE CHEST-SUPPORTED DUMBBELL ROW",
    "label": "INCLINE CHEST-SUPPORTED DUMBBELL ROW",
    "muscles": [
      "back",
      "biceps"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "biceps"
    ]
  },
  {
    "id": "INCLINE CLOSE GRIP BARBELL BENCH PRESS",
    "label": "INCLINE CLOSE GRIP BARBELL BENCH PRESS",
    "muscles": [
      "triceps",
      "chest",
      "shoulders"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "triceps"
    ],
    "secondaryMuscles": [
      "chest",
      "shoulders"
    ]
  },
  {
    "id": "INCLINE CRUNCHES",
    "label": "INCLINE CRUNCHES",
    "muscles": [
      "abs"
    ],
    "equipment": "bodyweight",
    "aliases": [],
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": [],
    "bw_coefficient": 0.35
  },
  {
    "id": "INCLINE DB Y-RAISE",
    "label": "INCLINE DB Y-RAISE",
    "muscles": [
      "shoulders",
      "back"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "shoulders"
    ],
    "secondaryMuscles": [
      "back"
    ]
  },
  {
    "id": "INCLINE DUMBBELL FLY",
    "label": "INCLINE DUMBBELL FLY",
    "muscles": [
      "chest",
      "shoulders"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "chest"
    ],
    "secondaryMuscles": [
      "shoulders"
    ]
  },
  {
    "id": "INCLINE DUMBBELL ROW",
    "label": "INCLINE DUMBBELL ROW",
    "muscles": [
      "back",
      "biceps"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "biceps"
    ]
  },
  {
    "id": "INCLINE OHP DB",
    "label": "INCLINE OHP DB",
    "muscles": [
      "shoulders",
      "chest",
      "triceps"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "shoulders"
    ],
    "secondaryMuscles": [
      "chest",
      "triceps"
    ]
  },
  {
    "id": "INCLINE PUSH UP",
    "label": "INCLINE PUSH UP",
    "muscles": [
      "chest",
      "shoulders",
      "triceps"
    ],
    "equipment": "bodyweight",
    "aliases": [],
    "primaryMuscles": [
      "chest"
    ],
    "secondaryMuscles": [
      "shoulders",
      "triceps"
    ],
    "bw_coefficient": 0.5
  },
  {
    "id": "INCLINE SKULL CRUSH",
    "label": "INCLINE SKULL CRUSH",
    "muscles": [
      "triceps"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "triceps"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "INCLINE SMITH PRESS",
    "label": "INCLINE SMITH PRESS",
    "muscles": [
      "shoulders",
      "chest",
      "triceps"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "shoulders"
    ],
    "secondaryMuscles": [
      "chest",
      "triceps"
    ]
  },
  {
    "id": "INVERTED LAT PULL DOWN",
    "label": "INVERTED LAT PULL DOWN",
    "muscles": [
      "back",
      "biceps"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "biceps"
    ]
  },
  {
    "id": "INVERTED ROWS",
    "label": "INVERTED ROWS",
    "muscles": [
      "back",
      "biceps"
    ],
    "equipment": "bodyweight",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "biceps"
    ],
    "bw_coefficient": 0.55
  },
  {
    "id": "JM PRESS",
    "label": "JM PRESS",
    "muscles": [
      "triceps",
      "chest"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "triceps"
    ],
    "secondaryMuscles": [
      "chest"
    ]
  },
  {
    "id": "KNEE PUSH-UPS",
    "label": "KNEE PUSH-UPS",
    "muscles": [
      "chest",
      "shoulders",
      "triceps"
    ],
    "equipment": "bodyweight",
    "aliases": [],
    "primaryMuscles": [
      "chest"
    ],
    "secondaryMuscles": [
      "shoulders",
      "triceps"
    ],
    "bw_coefficient": 0.5
  },
  {
    "id": "KNEE RAISES",
    "label": "KNEE RAISES",
    "muscles": [
      "abs"
    ],
    "equipment": "bodyweight",
    "aliases": [],
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": [],
    "bw_coefficient": 0.5
  },
  {
    "id": "KROC ROW",
    "label": "KROC ROW",
    "muscles": [
      "back",
      "biceps"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "biceps"
    ]
  },
  {
    "id": "LANDMINE PRESS",
    "label": "LANDMINE PRESS",
    "muscles": [
      "shoulders",
      "triceps",
      "chest"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "shoulders"
    ],
    "secondaryMuscles": [
      "triceps",
      "chest"
    ]
  },
  {
    "id": "LAT PULL DOWN",
    "label": "LAT PULL DOWN",
    "muscles": [
      "back",
      "biceps"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "biceps"
    ]
  },
  {
    "id": "LAT PULLDOWN - CROSS BODY SINGLE ARM",
    "label": "LAT PULLDOWN - CROSS BODY SINGLE ARM",
    "muscles": [
      "back",
      "biceps"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "biceps"
    ]
  },
  {
    "id": "LAT PULLDOWN (WIDE GRIP)",
    "label": "LAT PULLDOWN (WIDE GRIP)",
    "muscles": [
      "back",
      "biceps"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "biceps"
    ]
  },
  {
    "id": "LATERAL RAISES",
    "label": "LATERAL RAISES",
    "muscles": [
      "shoulders"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "shoulders"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "LATERAL ROWS ON CABLE, ONE ARMED",
    "label": "LATERAL ROWS ON CABLE, ONE ARMED",
    "muscles": [
      "back",
      "biceps"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "biceps"
    ]
  },
  {
    "id": "LEG CURLS (LAYING)",
    "label": "LEG CURLS (LAYING)",
    "muscles": [
      "hamstrings"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "hamstrings"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "LEG CURLS (SITTING)",
    "label": "LEG CURLS (SITTING)",
    "muscles": [
      "hamstrings"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "hamstrings"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "LEG CURLS (STANDING)",
    "label": "LEG CURLS (STANDING)",
    "muscles": [
      "hamstrings"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "hamstrings"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "LEG EXTENSION",
    "label": "LEG EXTENSION",
    "muscles": [
      "quads"
    ],
    "equipment": "machine",
    "aliases": [
      "LE"
    ],
    "primaryMuscles": [
      "quads"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "LEG PRESS",
    "label": "LEG PRESS",
    "muscles": [
      "quads",
      "glutes",
      "hamstrings"
    ],
    "equipment": "machine",
    "aliases": [
      "LP"
    ],
    "primaryMuscles": [
      "quads"
    ],
    "secondaryMuscles": [
      "glutes",
      "hamstrings"
    ],
    "is_king_compound": true
  },
  {
    "id": "LEG PRESS TOE PRESS",
    "label": "LEG PRESS TOE PRESS",
    "muscles": [
      "calves"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "calves"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "LEG PRESSES (NARROW)",
    "label": "LEG PRESSES (NARROW)",
    "muscles": [
      "quads",
      "glutes",
      "hamstrings"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "quads"
    ],
    "secondaryMuscles": [
      "glutes",
      "hamstrings"
    ],
    "is_king_compound": true
  },
  {
    "id": "LEG PRESSES (WIDE)",
    "label": "LEG PRESSES (WIDE)",
    "muscles": [
      "quads",
      "glutes",
      "hamstrings"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "quads"
    ],
    "secondaryMuscles": [
      "glutes",
      "hamstrings"
    ],
    "is_king_compound": true
  },
  {
    "id": "LEG RAISE",
    "label": "LEG RAISE",
    "muscles": [
      "abs"
    ],
    "equipment": "bodyweight",
    "aliases": [],
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": [],
    "bw_coefficient": 0.5
  },
  {
    "id": "LEG RAISES, STANDING",
    "label": "LEG RAISES, STANDING",
    "muscles": [
      "abs"
    ],
    "equipment": "bodyweight",
    "aliases": [],
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": [],
    "bw_coefficient": 0.35
  },
  {
    "id": "LEVERAGE MACHINE ISO ROW",
    "label": "LEVERAGE MACHINE ISO ROW",
    "muscles": [
      "back",
      "biceps"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "biceps"
    ]
  },
  {
    "id": "LONG-PULLEY (LOW ROW)",
    "label": "LONG-PULLEY (LOW ROW)",
    "muscles": [
      "back",
      "biceps"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "biceps"
    ]
  },
  {
    "id": "LYING TRICEPS EXTENSIONS",
    "label": "LYING TRICEPS EXTENSIONS",
    "muscles": [
      "triceps"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "triceps"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "LYING TRICEPS KICKBACK",
    "label": "LYING TRICEPS KICKBACK",
    "muscles": [
      "triceps"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "triceps"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "MACHINE CHEST PRESS",
    "label": "MACHINE CHEST PRESS",
    "muscles": [
      "chest",
      "shoulders",
      "triceps"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "chest"
    ],
    "secondaryMuscles": [
      "shoulders",
      "triceps"
    ]
  },
  {
    "id": "MACHINE HIP ABDUCTION",
    "label": "MACHINE HIP ABDUCTION",
    "muscles": [
      "glutes"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "glutes"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "MACHINE SIDE LATERAL RAISES",
    "label": "MACHINE SIDE LATERAL RAISES",
    "muscles": [
      "shoulders"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "shoulders"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "NECK EXTENSION",
    "label": "NECK EXTENSION",
    "muscles": [
      "back"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "NEUTRAL GRIP LAT PULLDOWN",
    "label": "NEUTRAL GRIP LAT PULLDOWN",
    "muscles": [
      "back",
      "biceps"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "biceps"
    ]
  },
  {
    "id": "NORDIC CURL",
    "label": "NORDIC CURL",
    "muscles": [
      "hamstrings"
    ],
    "equipment": "bodyweight",
    "aliases": [
      "NORDIC"
    ],
    "primaryMuscles": [
      "hamstrings"
    ],
    "secondaryMuscles": [],
    "bw_coefficient": 0.9
  },
  {
    "id": "OMNI CABLE CROSS-OVER",
    "label": "OMNI CABLE CROSS-OVER",
    "muscles": [
      "chest",
      "shoulders"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "chest"
    ],
    "secondaryMuscles": [
      "shoulders"
    ]
  },
  {
    "id": "ONE ARM OVERHEAD CABLE TRICEP EXTENSION",
    "label": "ONE ARM OVERHEAD CABLE TRICEP EXTENSION",
    "muscles": [
      "triceps"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "triceps"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "ONE ARMED PUSH-UPS",
    "label": "ONE ARMED PUSH-UPS",
    "muscles": [
      "chest",
      "shoulders",
      "triceps"
    ],
    "equipment": "bodyweight",
    "aliases": [],
    "primaryMuscles": [
      "chest"
    ],
    "secondaryMuscles": [
      "shoulders",
      "triceps"
    ],
    "bw_coefficient": 0.65
  },
  {
    "id": "OVERHAND CABLE CURL",
    "label": "OVERHAND CABLE CURL",
    "muscles": [
      "biceps",
      "forearms"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "biceps"
    ],
    "secondaryMuscles": [
      "forearms"
    ]
  },
  {
    "id": "OVERHEAD CABLE TRICEP EXTENSION",
    "label": "OVERHEAD CABLE TRICEP EXTENSION",
    "muscles": [
      "triceps"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "triceps"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "OVERHEAD PRESS",
    "label": "OVERHEAD PRESS",
    "muscles": [
      "shoulders",
      "triceps"
    ],
    "equipment": "barbell",
    "aliases": [
      "OHP",
      "STRICT PRESS"
    ],
    "primaryMuscles": [
      "shoulders"
    ],
    "secondaryMuscles": [
      "triceps"
    ]
  },
  {
    "id": "OVERHEAD TRICEPS EXTENSION",
    "label": "OVERHEAD TRICEPS EXTENSION",
    "muscles": [
      "triceps"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "triceps"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "PALLOF PRESS",
    "label": "PALLOF PRESS",
    "muscles": [
      "abs"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "PENDELAY ROWS",
    "label": "PENDELAY ROWS",
    "muscles": [
      "back",
      "biceps"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "biceps"
    ]
  },
  {
    "id": "PENDULUM SQUAT",
    "label": "PENDULUM SQUAT",
    "muscles": [
      "quads",
      "glutes",
      "hamstrings"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "quads"
    ],
    "secondaryMuscles": [
      "glutes",
      "hamstrings"
    ],
    "is_king_compound": true
  },
  {
    "id": "PIKE PUSH UPS",
    "label": "PIKE PUSH UPS",
    "muscles": [
      "shoulders",
      "triceps"
    ],
    "equipment": "bodyweight",
    "aliases": [],
    "primaryMuscles": [
      "shoulders"
    ],
    "secondaryMuscles": [
      "triceps"
    ],
    "bw_coefficient": 0.75
  },
  {
    "id": "PREACHER CURL - EXTERNALLY ROTATED",
    "label": "PREACHER CURL - EXTERNALLY ROTATED",
    "muscles": [
      "biceps"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "biceps"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "PREACHER CURL - INTERNALLY ROTATED",
    "label": "PREACHER CURL - INTERNALLY ROTATED",
    "muscles": [
      "biceps"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "biceps"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "PREACHER CURLS",
    "label": "PREACHER CURLS",
    "muscles": [
      "biceps"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "biceps"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "PULL-UPS",
    "label": "PULL-UPS",
    "muscles": [
      "back",
      "biceps"
    ],
    "equipment": "bodyweight",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "biceps"
    ],
    "bw_coefficient": 1.0
  },
  {
    "id": "PULL-UPS (NEUTRAL GRIP)",
    "label": "PULL-UPS (NEUTRAL GRIP)",
    "muscles": [
      "back",
      "biceps"
    ],
    "equipment": "bodyweight",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "biceps"
    ],
    "bw_coefficient": 1.0
  },
  {
    "id": "PULL-UPS (WIDE GRIP)",
    "label": "PULL-UPS (WIDE GRIP)",
    "muscles": [
      "back",
      "biceps"
    ],
    "equipment": "bodyweight",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "biceps"
    ],
    "bw_coefficient": 1.0
  },
  {
    "id": "PULLOVER MACHINE",
    "label": "PULLOVER MACHINE",
    "muscles": [
      "back",
      "chest"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "chest"
    ]
  },
  {
    "id": "PUSH PRESS",
    "label": "PUSH PRESS",
    "muscles": [
      "shoulders",
      "triceps",
      "quads"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "shoulders"
    ],
    "secondaryMuscles": [
      "triceps",
      "quads"
    ]
  },
  {
    "id": "PUSH-UPS",
    "label": "PUSH-UPS",
    "muscles": [
      "chest",
      "shoulders",
      "triceps"
    ],
    "equipment": "bodyweight",
    "aliases": [],
    "primaryMuscles": [
      "chest"
    ],
    "secondaryMuscles": [
      "shoulders",
      "triceps"
    ],
    "bw_coefficient": 0.65
  },
  {
    "id": "PUSH-UPS | DECLINE",
    "label": "PUSH-UPS | DECLINE",
    "muscles": [
      "chest",
      "shoulders",
      "triceps"
    ],
    "equipment": "bodyweight",
    "aliases": [],
    "primaryMuscles": [
      "chest"
    ],
    "secondaryMuscles": [
      "shoulders",
      "triceps"
    ],
    "bw_coefficient": 0.75
  },
  {
    "id": "PUSH-UPS | INCLINE",
    "label": "PUSH-UPS | INCLINE",
    "muscles": [
      "chest",
      "shoulders",
      "triceps"
    ],
    "equipment": "bodyweight",
    "aliases": [],
    "primaryMuscles": [
      "chest"
    ],
    "secondaryMuscles": [
      "shoulders",
      "triceps"
    ],
    "bw_coefficient": 0.5
  },
  {
    "id": "PUSH-UPS | PARALLETTES",
    "label": "PUSH-UPS | PARALLETTES",
    "muscles": [
      "chest",
      "shoulders",
      "triceps"
    ],
    "equipment": "bodyweight",
    "aliases": [],
    "primaryMuscles": [
      "chest"
    ],
    "secondaryMuscles": [
      "shoulders",
      "triceps"
    ],
    "bw_coefficient": 0.75
  },
  {
    "id": "RACK DEADLIFT",
    "label": "RACK DEADLIFT",
    "muscles": [
      "back",
      "glutes",
      "hamstrings",
      "abs"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "glutes",
      "hamstrings",
      "abs"
    ],
    "is_king_compound": true
  },
  {
    "id": "REAR DELT RAISE",
    "label": "REAR DELT RAISE",
    "muscles": [
      "shoulders",
      "back"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "shoulders"
    ],
    "secondaryMuscles": [
      "back"
    ],
    "is_isolation_override": true
  },
  {
    "id": "RENEGADE ROW",
    "label": "RENEGADE ROW",
    "muscles": [
      "back",
      "biceps"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "biceps"
    ]
  },
  {
    "id": "REVERSE CRUNCH",
    "label": "REVERSE CRUNCH",
    "muscles": [
      "abs"
    ],
    "equipment": "bodyweight",
    "aliases": [],
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": [],
    "bw_coefficient": 0.35
  },
  {
    "id": "REVERSE CURL",
    "label": "REVERSE CURL",
    "muscles": [
      "biceps",
      "forearms"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "biceps"
    ],
    "secondaryMuscles": [
      "forearms"
    ]
  },
  {
    "id": "REVERSE EZ BAR CABLE CURLS",
    "label": "REVERSE EZ BAR CABLE CURLS",
    "muscles": [
      "biceps",
      "forearms"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "biceps"
    ],
    "secondaryMuscles": [
      "forearms"
    ]
  },
  {
    "id": "REVERSE FLY STANDING",
    "label": "REVERSE FLY STANDING",
    "muscles": [
      "shoulders",
      "back"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "shoulders"
    ],
    "secondaryMuscles": [
      "back"
    ],
    "is_isolation_override": true
  },
  {
    "id": "REVERSE GRIP BENCH PRESS",
    "label": "REVERSE GRIP BENCH PRESS",
    "muscles": [
      "chest",
      "shoulders",
      "triceps"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "chest"
    ],
    "secondaryMuscles": [
      "shoulders",
      "triceps"
    ]
  },
  {
    "id": "REVERSE HYPEREXTENSION",
    "label": "REVERSE HYPEREXTENSION",
    "muscles": [
      "back",
      "glutes",
      "hamstrings"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "glutes",
      "hamstrings"
    ]
  },
  {
    "id": "REVERSE NORDIC CURL",
    "label": "REVERSE NORDIC CURL",
    "muscles": [
      "quads"
    ],
    "equipment": "bodyweight",
    "aliases": [],
    "primaryMuscles": [
      "quads"
    ],
    "secondaryMuscles": [],
    "bw_coefficient": 0.5
  },
  {
    "id": "REVERSE PREACHER CURL (CLOSE GRIP)",
    "label": "REVERSE PREACHER CURL (CLOSE GRIP)",
    "muscles": [
      "biceps",
      "forearms"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "biceps"
    ],
    "secondaryMuscles": [
      "forearms"
    ]
  },
  {
    "id": "REVERSE WOOD CHOPS",
    "label": "REVERSE WOOD CHOPS",
    "muscles": [
      "abs"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "ROTARY TORSO MACHINE",
    "label": "ROTARY TORSO MACHINE",
    "muscles": [
      "abs"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "ROWING SEATED, NARROW GRIP",
    "label": "ROWING SEATED, NARROW GRIP",
    "muscles": [
      "back",
      "biceps"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "biceps"
    ]
  },
  {
    "id": "SEATED CABLE MID TRAP SHRUG",
    "label": "SEATED CABLE MID TRAP SHRUG",
    "muscles": [
      "back"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "SEATED CABLE ROWS",
    "label": "SEATED CABLE ROWS",
    "muscles": [
      "back",
      "biceps"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "biceps"
    ]
  },
  {
    "id": "SEATED DUMBBELL CALF RAISE",
    "label": "SEATED DUMBBELL CALF RAISE",
    "muscles": [
      "calves"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "calves"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "SEATED DUMBBELL CURLS",
    "label": "SEATED DUMBBELL CURLS",
    "muscles": [
      "biceps"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "biceps"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "SEATED DUMBBELL SIDE LATERAL",
    "label": "SEATED DUMBBELL SIDE LATERAL",
    "muscles": [
      "shoulders"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "shoulders"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "SEATED HIP ABDUCTION",
    "label": "SEATED HIP ABDUCTION",
    "muscles": [
      "glutes"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "glutes"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "SEATED HIP ADDUCTION",
    "label": "SEATED HIP ADDUCTION",
    "muscles": [
      "quads",
      "glutes"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "quads"
    ],
    "secondaryMuscles": [
      "glutes"
    ]
  },
  {
    "id": "SEATED KNEE TUCK",
    "label": "SEATED KNEE TUCK",
    "muscles": [
      "abs"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "SEATED MACHINE ROW",
    "label": "SEATED MACHINE ROW",
    "muscles": [
      "back",
      "biceps"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "biceps"
    ]
  },
  {
    "id": "SEATED TRICEPS PRESS",
    "label": "SEATED TRICEPS PRESS",
    "muscles": [
      "triceps"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "triceps"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "SEATED V-GRIP ROW",
    "label": "SEATED V-GRIP ROW",
    "muscles": [
      "back",
      "biceps"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "biceps"
    ]
  },
  {
    "id": "SHOTGUN ROW",
    "label": "SHOTGUN ROW",
    "muscles": [
      "back",
      "biceps"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "biceps"
    ]
  },
  {
    "id": "SHOULDER EXTERNAL ROTATION WITH DUMBBELL",
    "label": "SHOULDER EXTERNAL ROTATION WITH DUMBBELL",
    "muscles": [
      "shoulders"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "shoulders"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "SHOULDER INTERNAL ROTATION (CABLE)",
    "label": "SHOULDER INTERNAL ROTATION (CABLE)",
    "muscles": [
      "shoulders"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "shoulders"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "SHOULDER PRESS (DUMBBELL)",
    "label": "SHOULDER PRESS (DUMBBELL)",
    "muscles": [
      "shoulders",
      "triceps"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "shoulders"
    ],
    "secondaryMuscles": [
      "triceps"
    ]
  },
  {
    "id": "SHOULDER PRESS, ON MACHINE",
    "label": "SHOULDER PRESS, ON MACHINE",
    "muscles": [
      "shoulders",
      "triceps"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "shoulders"
    ],
    "secondaryMuscles": [
      "triceps"
    ]
  },
  {
    "id": "SHRUGS, BARBELLS",
    "label": "SHRUGS, BARBELLS",
    "muscles": [
      "back"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "SHRUGS, DUMBBELLS",
    "label": "SHRUGS, DUMBBELLS",
    "muscles": [
      "back"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "SIDE CRUNCH",
    "label": "SIDE CRUNCH",
    "muscles": [
      "abs"
    ],
    "equipment": "bodyweight",
    "aliases": [],
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": [],
    "bw_coefficient": 0.35
  },
  {
    "id": "SIDE DUMBBELL TRUNK FLEXION",
    "label": "SIDE DUMBBELL TRUNK FLEXION",
    "muscles": [
      "abs"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "SIDE LATERAL RAISE - BACK (CABLE)",
    "label": "SIDE LATERAL RAISE - BACK (CABLE)",
    "muscles": [
      "shoulders"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "shoulders"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "SIDE LATERAL RAISE - FRONT (CABLE)",
    "label": "SIDE LATERAL RAISE - FRONT (CABLE)",
    "muscles": [
      "shoulders"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "shoulders"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "SIDE LATERAL RAISE (CABLE)",
    "label": "SIDE LATERAL RAISE (CABLE)",
    "muscles": [
      "shoulders"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "shoulders"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "SIDE STRAIGHT-ARM PULLDOWN (CABLE)",
    "label": "SIDE STRAIGHT-ARM PULLDOWN (CABLE)",
    "muscles": [
      "back"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "SINGLE LEG EXTENSION",
    "label": "SINGLE LEG EXTENSION",
    "muscles": [
      "quads"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "quads"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "SINGLE-ARM PREACHER CURL",
    "label": "SINGLE-ARM PREACHER CURL",
    "muscles": [
      "biceps"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "biceps"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "SINGLE-LEG DEADLIFT WITH DUMBBELL",
    "label": "SINGLE-LEG DEADLIFT WITH DUMBBELL",
    "muscles": [
      "hamstrings",
      "glutes",
      "back"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "hamstrings"
    ],
    "secondaryMuscles": [
      "glutes",
      "back"
    ]
  },
  {
    "id": "SIT-UPS",
    "label": "SIT-UPS",
    "muscles": [
      "abs"
    ],
    "equipment": "bodyweight",
    "aliases": [],
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": [],
    "bw_coefficient": 0.35
  },
  {
    "id": "SITTING CALF RAISES",
    "label": "SITTING CALF RAISES",
    "muscles": [
      "calves"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "calves"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "SKULLCRUSHER SZ-BAR",
    "label": "SKULLCRUSHER SZ-BAR",
    "muscles": [
      "triceps"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "triceps"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "SMITH MACHINE CLOSE-GRIP BENCH PRESS",
    "label": "SMITH MACHINE CLOSE-GRIP BENCH PRESS",
    "muscles": [
      "triceps",
      "chest",
      "shoulders"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "triceps"
    ],
    "secondaryMuscles": [
      "chest",
      "shoulders"
    ]
  },
  {
    "id": "SMITH MACHINE SPLIT SQUAT",
    "label": "SMITH MACHINE SPLIT SQUAT",
    "muscles": [
      "quads",
      "glutes"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "quads"
    ],
    "secondaryMuscles": [
      "glutes"
    ]
  },
  {
    "id": "SMITH MACHINE SQUAT",
    "label": "SMITH MACHINE SQUAT",
    "muscles": [
      "quads",
      "glutes",
      "back"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "quads"
    ],
    "secondaryMuscles": [
      "glutes",
      "back"
    ],
    "is_king_compound": true
  },
  {
    "id": "SPIDER CURL",
    "label": "SPIDER CURL",
    "muscles": [
      "biceps"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "biceps"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "STANDING CALF RAISES",
    "label": "STANDING CALF RAISES",
    "muscles": [
      "calves"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "calves"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "STANDING SIDE CRUNCHES",
    "label": "STANDING SIDE CRUNCHES",
    "muscles": [
      "abs"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "STIFF-LEGGED DEADLIFTS",
    "label": "STIFF-LEGGED DEADLIFTS",
    "muscles": [
      "hamstrings",
      "glutes",
      "back",
      "abs"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "hamstrings"
    ],
    "secondaryMuscles": [
      "glutes",
      "back",
      "abs"
    ],
    "is_king_compound": true
  },
  {
    "id": "STRAIGHT BAR CABLE FRONT RAISE",
    "label": "STRAIGHT BAR CABLE FRONT RAISE",
    "muscles": [
      "shoulders"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "shoulders"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "STRAIGHT-ARM PULL DOWN (BAR ATTACHMENT)",
    "label": "STRAIGHT-ARM PULL DOWN (BAR ATTACHMENT)",
    "muscles": [
      "back"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "STRAIGHT-ARM PULL DOWN (ROPE ATTACHMENT)",
    "label": "STRAIGHT-ARM PULL DOWN (ROPE ATTACHMENT)",
    "muscles": [
      "back"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "SUMO DEADLIFT",
    "label": "SUMO DEADLIFT",
    "muscles": [
      "glutes",
      "hamstrings",
      "back",
      "quads"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "glutes",
      "hamstrings"
    ],
    "secondaryMuscles": [
      "back",
      "quads"
    ],
    "is_king_compound": true
  },
  {
    "id": "SUMO SQUATS",
    "label": "SUMO SQUATS",
    "muscles": [
      "quads",
      "glutes",
      "hamstrings"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "quads"
    ],
    "secondaryMuscles": [
      "glutes",
      "hamstrings"
    ],
    "is_king_compound": true
  },
  {
    "id": "T-BAR ROW",
    "label": "T-BAR ROW",
    "muscles": [
      "back",
      "biceps"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "biceps"
    ]
  },
  {
    "id": "THRUSTER",
    "label": "THRUSTER",
    "muscles": [
      "quads",
      "shoulders",
      "glutes",
      "triceps"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "quads",
      "shoulders"
    ],
    "secondaryMuscles": [
      "glutes",
      "triceps"
    ]
  },
  {
    "id": "TRAP BAR SQUAT",
    "label": "TRAP BAR SQUAT",
    "muscles": [
      "quads",
      "glutes",
      "back"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "quads"
    ],
    "secondaryMuscles": [
      "glutes",
      "back"
    ],
    "is_king_compound": true
  },
  {
    "id": "TRAP-3 RAISE",
    "label": "TRAP-3 RAISE",
    "muscles": [
      "shoulders",
      "back"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "shoulders"
    ],
    "secondaryMuscles": [
      "back"
    ]
  },
  {
    "id": "TRICEP DUMBBELL KICKBACK",
    "label": "TRICEP DUMBBELL KICKBACK",
    "muscles": [
      "triceps"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "triceps"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "TRICEP ROPE PUSHDOWNS",
    "label": "TRICEP ROPE PUSHDOWNS",
    "muscles": [
      "triceps"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "triceps"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "TRICEPS DIPS (ASSISTED)",
    "label": "TRICEPS DIPS (ASSISTED)",
    "muscles": [
      "triceps"
    ],
    "equipment": "bodyweight",
    "aliases": [],
    "primaryMuscles": [
      "triceps"
    ],
    "secondaryMuscles": [],
    "bw_coefficient": 0.5
  },
  {
    "id": "TRICEPS EXTENSIONS ON CABLE",
    "label": "TRICEPS EXTENSIONS ON CABLE",
    "muscles": [
      "triceps"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "triceps"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "TRICEPS PUSHDOWN",
    "label": "TRICEPS PUSHDOWN",
    "muscles": [
      "triceps"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "triceps"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "TRUNK ROTATION WITH CABLE",
    "label": "TRUNK ROTATION WITH CABLE",
    "muscles": [
      "abs"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "UNDERHAND LAT PULL DOWN",
    "label": "UNDERHAND LAT PULL DOWN",
    "muscles": [
      "back",
      "biceps"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "back"
    ],
    "secondaryMuscles": [
      "biceps"
    ]
  },
  {
    "id": "UPRIGHT ROW, SZ-BAR",
    "label": "UPRIGHT ROW, SZ-BAR",
    "muscles": [
      "shoulders",
      "back"
    ],
    "equipment": "barbell",
    "aliases": [],
    "primaryMuscles": [
      "shoulders"
    ],
    "secondaryMuscles": [
      "back"
    ]
  },
  {
    "id": "W-RAISE",
    "label": "W-RAISE",
    "muscles": [
      "shoulders",
      "back"
    ],
    "equipment": "machine",
    "aliases": [],
    "primaryMuscles": [
      "shoulders"
    ],
    "secondaryMuscles": [
      "back"
    ]
  },
  {
    "id": "WALKING LUNGES",
    "label": "WALKING LUNGES",
    "muscles": [
      "quads",
      "glutes"
    ],
    "equipment": "bodyweight",
    "aliases": [],
    "primaryMuscles": [
      "quads"
    ],
    "secondaryMuscles": [
      "glutes"
    ],
    "bw_coefficient": 0.85
  },
  {
    "id": "WRIST CURL, CABLE",
    "label": "WRIST CURL, CABLE",
    "muscles": [
      "forearms"
    ],
    "equipment": "cable",
    "aliases": [],
    "primaryMuscles": [
      "forearms"
    ],
    "secondaryMuscles": []
  },
  {
    "id": "ZOTTMAN CURL",
    "label": "ZOTTMAN CURL",
    "muscles": [
      "biceps",
      "forearms"
    ],
    "equipment": "dumbbell",
    "aliases": [],
    "primaryMuscles": [
      "biceps"
    ],
    "secondaryMuscles": [
      "forearms"
    ]
  }
]

// Backward-compat layer: every exercise gets a `muscle` field === muscles[0]
// so older consumers reading the singular field continue working.
const _withMuscle = (e) => ({ ...e, muscle: e.muscles[0] })
const _ALL = ALL_EXERCISES.map(_withMuscle)

const CANONICAL_EXERCISE = {
  "chest": "BENCH PRESS",
  "shoulders": "OVERHEAD PRESS",
  "back": "BARBELL ROW",
  "forearms": "WRIST CURL",
  "quads": "SQUAT",
  "hamstrings": "ROMANIAN DEADLIFT",
  "calves": "STANDING CALF RAISE",
  "biceps": "BARBELL CURL",
  "triceps": "SKULL CRUSHER",
  "glutes": "HIP THRUST",
  "abs": "PLANK"
}

export function exercisesByMuscle(muscleId) {
  return _ALL.filter(e => e.muscles.includes(muscleId))
}

export function canonicalExerciseFor(muscleId) {
  const target = CANONICAL_EXERCISE[muscleId]
  if (target) {
    const found = _ALL.find(e => e.id === target && e.muscles.includes(muscleId))
    if (found) return found.id
  }
  const list = exercisesByMuscle(muscleId)
  return list[0]?.id || null
}

export function searchExercises(muscleId, query) {
  const list = exercisesByMuscle(muscleId)
  if (!query) return list
  const q = query.trim().toLowerCase()
  return list.filter(e =>
    e.label.toLowerCase().includes(q) ||
    e.aliases.some(a => a.toLowerCase().includes(q))
  )
}
