// AUTO-GENERATED by scripts/import-wger.js — do not edit by hand.
// Source: wger.de exercise database (CC-BY-SA 4.0)
// Re-run with: npm run import:exercises
// Last imported: 2026-05-03T07:05:23.744Z
// Exercise count: 502

export const ALL_EXERCISES = [
  {
    "id": "1 LEG BOX SQUAT",
    "label": "1 LEG BOX SQUAT",
    "muscles": [
      "hamstrings",
      "quads"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "1-ARM HALF-KNEELING LAT PULLDOWN",
    "label": "1-ARM HALF-KNEELING LAT PULLDOWN",
    "muscles": [
      "back"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "3008 ABDOMINAL CRUNCH",
    "label": "3008 ABDOMINAL CRUNCH",
    "muscles": [
      "abs"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "AB WHEEL",
    "label": "AB WHEEL",
    "muscles": [
      "abs"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "ABDOMINAL CRUNCH",
    "label": "ABDOMINAL CRUNCH",
    "muscles": [
      "abs"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "ABDOMINAL DRAW-IN",
    "label": "ABDOMINAL DRAW-IN",
    "muscles": [
      "abs"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "ABDOMINAL STABILIZATION",
    "label": "ABDOMINAL STABILIZATION",
    "muscles": [
      "abs"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "ALTERNATE BACK LUNGES",
    "label": "ALTERNATE BACK LUNGES",
    "muscles": [
      "glutes",
      "quads"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "ALTERNATING BICEPS CURLS WITH DUMBBELL",
    "label": "ALTERNATING BICEPS CURLS WITH DUMBBELL",
    "muscles": [
      "biceps"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "ALTERNATING DUMBBELL HAMMER CURL",
    "label": "ALTERNATING DUMBBELL HAMMER CURL",
    "muscles": [
      "biceps"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "ALTERNATING HIGH CABLE ROW",
    "label": "ALTERNATING HIGH CABLE ROW",
    "muscles": [
      "back"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "ALTERNATIVE DB GORILLA ROWS",
    "label": "ALTERNATIVE DB GORILLA ROWS",
    "muscles": [
      "back"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "ARABESQUE",
    "label": "ARABESQUE",
    "muscles": [
      "hamstrings",
      "glutes"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "ARCHER PULL UP",
    "label": "ARCHER PULL UP",
    "muscles": [
      "back",
      "biceps"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "ARCO FEMORALE UNA GAMBA",
    "label": "ARCO FEMORALE UNA GAMBA",
    "muscles": [
      "glutes",
      "back"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "ARM RAISES (T/Y/I)",
    "label": "ARM RAISES (T/Y/I)",
    "muscles": [
      "shoulders",
      "back",
      "abs"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "ASSISTED PULL-UP",
    "label": "ASSISTED PULL-UP",
    "muscles": [
      "back",
      "shoulders",
      "biceps",
      "abs"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "AUSTRALIAN PULL-UPS",
    "label": "AUSTRALIAN PULL-UPS",
    "muscles": [
      "shoulders",
      "biceps",
      "back"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "BACK BRIDGE",
    "label": "BACK BRIDGE",
    "muscles": [
      "shoulders",
      "hamstrings",
      "calves",
      "back",
      "triceps"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "BARBELL AB ROLLOUT",
    "label": "BARBELL AB ROLLOUT",
    "muscles": [
      "abs"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "BARBELL FULL SQUAT",
    "label": "BARBELL FULL SQUAT",
    "muscles": [
      "hamstrings",
      "glutes",
      "quads",
      "calves",
      "abs"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "BARBELL HIP THRUST",
    "label": "BARBELL HIP THRUST",
    "muscles": [
      "glutes"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "BARBELL LUNGES STANDING",
    "label": "BARBELL LUNGES STANDING",
    "muscles": [
      "quads",
      "glutes"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "BARBELL ROMANIAN DEADLIFT (RDL)",
    "label": "BARBELL ROMANIAN DEADLIFT (RDL)",
    "muscles": [
      "back"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "BARBELL ROW (OVERHAND)",
    "label": "BARBELL ROW (OVERHAND)",
    "muscles": [
      "back"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "BARBELL ROW (UNDERHAND)",
    "label": "BARBELL ROW (UNDERHAND)",
    "muscles": [
      "back"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "BARBELL SILVERBACK SHRUG",
    "label": "BARBELL SILVERBACK SHRUG",
    "muscles": [
      "back"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "BARBELL SQUAT",
    "label": "BARBELL SQUAT",
    "muscles": [
      "hamstrings",
      "glutes",
      "abs"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "BARBELL STEP BACK LUNGE",
    "label": "BARBELL STEP BACK LUNGE",
    "muscles": [
      "quads"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "BARBELL TRICEPS EXTENSION",
    "label": "BARBELL TRICEPS EXTENSION",
    "muscles": [
      "triceps",
      "shoulders",
      "chest"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "BARBELL WRIST CURL",
    "label": "BARBELL WRIST CURL",
    "muscles": [
      "shoulders",
      "hamstrings",
      "biceps",
      "abs"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "BAYESIAN CURL",
    "label": "BAYESIAN CURL",
    "muscles": [
      "biceps"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "BEHIND THE BACK CABLE LATERAL RAISE",
    "label": "BEHIND THE BACK CABLE LATERAL RAISE",
    "muscles": [
      "shoulders",
      "back"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "BELT SQUAT",
    "label": "BELT SQUAT",
    "muscles": [
      "glutes",
      "quads",
      "hamstrings"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "BENCH PRESS",
    "label": "BENCH PRESS",
    "muscles": [
      "chest",
      "shoulders",
      "triceps"
    ],
    "equipment": "barbell",
    "aliases": [
      "BP",
      "BENCH"
    ]
  },
  {
    "id": "BENCH PRESS NARROW GRIP",
    "label": "BENCH PRESS NARROW GRIP",
    "muscles": [
      "triceps",
      "shoulders",
      "chest"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "BENCHPRESS DUMBBELLS",
    "label": "BENCHPRESS DUMBBELLS",
    "muscles": [
      "chest",
      "shoulders",
      "triceps"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "BENT HIGH PULLS",
    "label": "BENT HIGH PULLS",
    "muscles": [
      "back"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "BENT OVER CABLE FLYE",
    "label": "BENT OVER CABLE FLYE",
    "muscles": [
      "chest"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "BENT OVER DUMBBELL ROWS",
    "label": "BENT OVER DUMBBELL ROWS",
    "muscles": [
      "back"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "BENT OVER ROWING",
    "label": "BENT OVER ROWING",
    "muscles": [
      "back",
      "shoulders",
      "biceps"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "BENT OVER ROWING REVERSE",
    "label": "BENT OVER ROWING REVERSE",
    "muscles": [
      "back",
      "shoulders",
      "biceps"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "BICEPS CLOSE GRIP PULL DOWN",
    "label": "BICEPS CLOSE GRIP PULL DOWN",
    "muscles": [
      "biceps",
      "shoulders",
      "back"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "BICEPS CURL MACHINE",
    "label": "BICEPS CURL MACHINE",
    "muscles": [
      "biceps"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "BICEPS CURL WITH CABLE",
    "label": "BICEPS CURL WITH CABLE",
    "muscles": [
      "biceps"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "BICEPS CURLS WITH BARBELL",
    "label": "BICEPS CURLS WITH BARBELL",
    "muscles": [
      "biceps"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "BICEPS CURLS WITH DUMBBELL",
    "label": "BICEPS CURLS WITH DUMBBELL",
    "muscles": [
      "biceps"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "BICEPS CURLS WITH SZ-BAR",
    "label": "BICEPS CURLS WITH SZ-BAR",
    "muscles": [
      "biceps"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "BICYCLE CRUNCHES",
    "label": "BICYCLE CRUNCHES",
    "muscles": [
      "abs"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "BIRD DOG",
    "label": "BIRD DOG",
    "muscles": [
      "abs",
      "shoulders",
      "glutes"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "BIZEPS CURLS TRIFECTA",
    "label": "BIZEPS CURLS TRIFECTA",
    "muscles": [
      "biceps"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "BODYWEIGHT BICEPS CURL",
    "label": "BODYWEIGHT BICEPS CURL",
    "muscles": [
      "biceps"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "BOX SQUAT",
    "label": "BOX SQUAT",
    "muscles": [
      "glutes",
      "quads",
      "calves"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "BRACED SQUAT",
    "label": "BRACED SQUAT",
    "muscles": [
      "quads",
      "glutes"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "BULGARIAN SQUAT WITH DUMBBELLS",
    "label": "BULGARIAN SQUAT WITH DUMBBELLS",
    "muscles": [
      "glutes",
      "quads",
      "hamstrings"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "BUTTERFLY",
    "label": "BUTTERFLY",
    "muscles": [
      "chest",
      "shoulders"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "BUTTERFLY NARROW GRIP",
    "label": "BUTTERFLY NARROW GRIP",
    "muscles": [
      "chest"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "BUTTERFLY REVERSE",
    "label": "BUTTERFLY REVERSE",
    "muscles": [
      "shoulders"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "BUTTERFLY SIT UP",
    "label": "BUTTERFLY SIT UP",
    "muscles": [
      "abs"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "BUTTERFLY SUPERMAN",
    "label": "BUTTERFLY SUPERMAN",
    "muscles": [
      "back"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "CABLE CHEST PRESS - DECLINE",
    "label": "CABLE CHEST PRESS - DECLINE",
    "muscles": [
      "chest",
      "triceps"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "CABLE CHEST PRESS - INCLINE",
    "label": "CABLE CHEST PRESS - INCLINE",
    "muscles": [
      "chest",
      "triceps"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "CABLE CONCENTRATION CURL",
    "label": "CABLE CONCENTRATION CURL",
    "muscles": [
      "biceps"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "CABLE CROSS-OVER",
    "label": "CABLE CROSS-OVER",
    "muscles": [
      "chest",
      "shoulders"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "CABLE CURLS",
    "label": "CABLE CURLS",
    "muscles": [
      "biceps"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "CABLE EXTERNAL ROTATION",
    "label": "CABLE EXTERNAL ROTATION",
    "muscles": [
      "shoulders"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "CABLE FLY",
    "label": "CABLE FLY",
    "muscles": [
      "chest"
    ],
    "equipment": "cable",
    "aliases": [
      "CF"
    ]
  },
  {
    "id": "CABLE FLY LOWER CHEST",
    "label": "CABLE FLY LOWER CHEST",
    "muscles": [
      "chest"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "CABLE FLY MIDDLE CHEST",
    "label": "CABLE FLY MIDDLE CHEST",
    "muscles": [
      "chest"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "CABLE FLY UPPER CHEST",
    "label": "CABLE FLY UPPER CHEST",
    "muscles": [
      "chest"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "CABLE FRONT RAISE WITH A SMALL BAR",
    "label": "CABLE FRONT RAISE WITH A SMALL BAR",
    "muscles": [
      "shoulders"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "CABLE LATERAL RAISES (SINGLE ARM)",
    "label": "CABLE LATERAL RAISES (SINGLE ARM)",
    "muscles": [
      "shoulders"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "CABLE PRESS AROUND",
    "label": "CABLE PRESS AROUND",
    "muscles": [
      "shoulders",
      "chest",
      "triceps",
      "biceps"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "CABLE PULL THROUGH",
    "label": "CABLE PULL THROUGH",
    "muscles": [
      "glutes",
      "hamstrings",
      "calves",
      "quads"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "CABLE REAR DELT FLY",
    "label": "CABLE REAR DELT FLY",
    "muscles": [
      "shoulders",
      "back",
      "triceps"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "CABLE SHRUG-IN",
    "label": "CABLE SHRUG-IN",
    "muscles": [
      "back"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "CABLE TRI EXTENSION - EXTERNAL ROTATION",
    "label": "CABLE TRI EXTENSION - EXTERNAL ROTATION",
    "muscles": [
      "triceps"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "CABLE TRI EXTENSION - INTERNAL ROTATION",
    "label": "CABLE TRI EXTENSION - INTERNAL ROTATION",
    "muscles": [
      "triceps"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "CABLE TRICEP KICKBACK",
    "label": "CABLE TRICEP KICKBACK",
    "muscles": [
      "triceps"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "CABLE TRICEPS PRESS",
    "label": "CABLE TRICEPS PRESS",
    "muscles": [
      "triceps"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "CABLE WOODCHOPPERS",
    "label": "CABLE WOODCHOPPERS",
    "muscles": [
      "abs"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "CALF PRESS USING LEG PRESS MACHINE",
    "label": "CALF PRESS USING LEG PRESS MACHINE",
    "muscles": [
      "calves"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "CALF RAISE USING HACK SQUAT MACHINE",
    "label": "CALF RAISE USING HACK SQUAT MACHINE",
    "muscles": [
      "calves"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "CALF RAISES ON HACKENSCHMITT MACHINE",
    "label": "CALF RAISES ON HACKENSCHMITT MACHINE",
    "muscles": [
      "calves"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "CALF RAISES, LEFT LEG",
    "label": "CALF RAISES, LEFT LEG",
    "muscles": [
      "calves"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "CALF RAISES, ONE LEGGED",
    "label": "CALF RAISES, ONE LEGGED",
    "muscles": [
      "calves"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "CHEST PRESS",
    "label": "CHEST PRESS",
    "muscles": [
      "chest"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "CHEST-SUPPORTED REAR DELT RAISE",
    "label": "CHEST-SUPPORTED REAR DELT RAISE",
    "muscles": [
      "shoulders",
      "back"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "CHIN-UPS",
    "label": "CHIN-UPS",
    "muscles": [
      "back"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "CLAMSHELL",
    "label": "CLAMSHELL",
    "muscles": [
      "glutes",
      "abs"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "CLAP PUSH-UP",
    "label": "CLAP PUSH-UP",
    "muscles": [
      "chest",
      "shoulders",
      "abs",
      "triceps"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "CLAPS OVER THE HEAD",
    "label": "CLAPS OVER THE HEAD",
    "muscles": [
      "shoulders"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "CLOSE-GRIP BENCH PRESS",
    "label": "CLOSE-GRIP BENCH PRESS",
    "muscles": [
      "triceps",
      "chest"
    ],
    "equipment": "barbell",
    "aliases": [
      "CGBP"
    ]
  },
  {
    "id": "CLOSE-GRIP LAT PULL DOWN",
    "label": "CLOSE-GRIP LAT PULL DOWN",
    "muscles": [
      "back"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "CLOSE-GRIP PRESS-UPS",
    "label": "CLOSE-GRIP PRESS-UPS",
    "muscles": [
      "biceps",
      "back",
      "chest",
      "shoulders",
      "triceps"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "COMMANDO PULL-UPS",
    "label": "COMMANDO PULL-UPS",
    "muscles": [
      "shoulders",
      "biceps",
      "back"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "CONCENTRATION CURL",
    "label": "CONCENTRATION CURL",
    "muscles": [
      "biceps"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "COPENHAGEN ADDUCTION EXERCISE",
    "label": "COPENHAGEN ADDUCTION EXERCISE",
    "muscles": [
      "glutes",
      "quads",
      "abs",
      "back"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "CORE ROTATION",
    "label": "CORE ROTATION",
    "muscles": [
      "quads",
      "abs"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "COSSACK SQUAT",
    "label": "COSSACK SQUAT",
    "muscles": [
      "glutes",
      "quads",
      "calves",
      "abs"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "CROSS-BENCH DUMBBELL PULLOVERS",
    "label": "CROSS-BENCH DUMBBELL PULLOVERS",
    "muscles": [
      "back",
      "chest"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "CROSS-BODY CABLE Y-RAISE",
    "label": "CROSS-BODY CABLE Y-RAISE",
    "muscles": [
      "shoulders",
      "back"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "CRUNCHES",
    "label": "CRUNCHES",
    "muscles": [
      "abs"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "CRUNCHES ON MACHINE",
    "label": "CRUNCHES ON MACHINE",
    "muscles": [
      "abs"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "CRUNCHES WITH CABLE",
    "label": "CRUNCHES WITH CABLE",
    "muscles": [
      "abs"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "CRUNCHES WITH LEGS UP",
    "label": "CRUNCHES WITH LEGS UP",
    "muscles": [
      "abs"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "CURL - WITH SHOULDER ELEVATED",
    "label": "CURL - WITH SHOULDER ELEVATED",
    "muscles": [
      "biceps"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "CURL WITH KETTLEBELL TWO HANDS",
    "label": "CURL WITH KETTLEBELL TWO HANDS",
    "muscles": [
      "biceps"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "DB CROSS BODY HAMMER CURLS",
    "label": "DB CROSS BODY HAMMER CURLS",
    "muscles": [
      "biceps"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "DB SKULL CRUSHERS",
    "label": "DB SKULL CRUSHERS",
    "muscles": [
      "triceps"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "DB UCV",
    "label": "DB UCV",
    "muscles": [
      "chest",
      "shoulders"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "DB UNDERHAND BENCH PRESS",
    "label": "DB UNDERHAND BENCH PRESS",
    "muscles": [
      "chest",
      "shoulders"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "DB UPPER CHEST VARIATION",
    "label": "DB UPPER CHEST VARIATION",
    "muscles": [
      "chest",
      "shoulders"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "DEADLIFTS",
    "label": "DEADLIFTS",
    "muscles": [
      "back",
      "glutes"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "DECLINE BENCH LEG RAISE",
    "label": "DECLINE BENCH LEG RAISE",
    "muscles": [
      "abs"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "DECLINE BENCH PRESS BARBELL",
    "label": "DECLINE BENCH PRESS BARBELL",
    "muscles": [
      "chest"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "DECLINE BENCH PRESS DUMBBELL",
    "label": "DECLINE BENCH PRESS DUMBBELL",
    "muscles": [
      "chest"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "DECLINE PUSHUPS",
    "label": "DECLINE PUSHUPS",
    "muscles": [
      "chest",
      "shoulders"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "DEFICIT DEADLIFT",
    "label": "DEFICIT DEADLIFT",
    "muscles": [
      "hamstrings",
      "glutes",
      "back",
      "abs",
      "calves"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "DEFICIT PUSH UPS",
    "label": "DEFICIT PUSH UPS",
    "muscles": [
      "chest",
      "triceps"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "DIAMOND PUSH UPS",
    "label": "DIAMOND PUSH UPS",
    "muscles": [
      "triceps",
      "chest"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "DIPS",
    "label": "DIPS",
    "muscles": [
      "chest",
      "triceps"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "DIPS BETWEEN TWO BENCHES",
    "label": "DIPS BETWEEN TWO BENCHES",
    "muscles": [
      "triceps"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "DOUBLE KETTLEBELL FRONT SQUAT",
    "label": "DOUBLE KETTLEBELL FRONT SQUAT",
    "muscles": [
      "glutes",
      "quads",
      "hamstrings",
      "calves",
      "abs"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "DOUBLE LEG CALF RAISE",
    "label": "DOUBLE LEG CALF RAISE",
    "muscles": [
      "calves"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "DOUBLE-LEG ABDOMINAL PRESS",
    "label": "DOUBLE-LEG ABDOMINAL PRESS",
    "muscles": [
      "abs"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "DRAG PUSHDOWN",
    "label": "DRAG PUSHDOWN",
    "muscles": [
      "triceps"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "DRAGON SQUAT",
    "label": "DRAGON SQUAT",
    "muscles": [
      "quads",
      "hamstrings",
      "calves",
      "glutes"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "DROP CURL",
    "label": "DROP CURL",
    "muscles": [
      "biceps"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "DUMBBELL BENCH PRESS",
    "label": "DUMBBELL BENCH PRESS",
    "muscles": [
      "chest",
      "shoulders",
      "triceps"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "DUMBBELL BENT OVER FACE PULL",
    "label": "DUMBBELL BENT OVER FACE PULL",
    "muscles": [
      "shoulders",
      "back"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "DUMBBELL BENT OVER ROW",
    "label": "DUMBBELL BENT OVER ROW",
    "muscles": [
      "shoulders",
      "biceps",
      "back",
      "triceps"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "DUMBBELL BICEP CURL TO PRESS",
    "label": "DUMBBELL BICEP CURL TO PRESS",
    "muscles": [
      "biceps"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "DUMBBELL BRADFORD PRESS",
    "label": "DUMBBELL BRADFORD PRESS",
    "muscles": [
      "shoulders"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "DUMBBELL CHEAT CURL",
    "label": "DUMBBELL CHEAT CURL",
    "muscles": [
      "biceps"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "DUMBBELL CHEST PRESS",
    "label": "DUMBBELL CHEST PRESS",
    "muscles": [
      "chest",
      "shoulders",
      "triceps"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "DUMBBELL CLOSE GRIP BENCH PRESS",
    "label": "DUMBBELL CLOSE GRIP BENCH PRESS",
    "muscles": [
      "chest",
      "triceps"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "DUMBBELL CONCENTRATION CURL",
    "label": "DUMBBELL CONCENTRATION CURL",
    "muscles": [
      "biceps"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "DUMBBELL CRUNCHES",
    "label": "DUMBBELL CRUNCHES",
    "muscles": [
      "abs"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "DUMBBELL CURL",
    "label": "DUMBBELL CURL",
    "muscles": [
      "biceps",
      "shoulders",
      "abs"
    ],
    "equipment": "dumbbell",
    "aliases": [
      "DBC"
    ]
  },
  {
    "id": "DUMBBELL DRAG CURLS",
    "label": "DUMBBELL DRAG CURLS",
    "muscles": [
      "biceps"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "DUMBBELL FLOOR PRESS",
    "label": "DUMBBELL FLOOR PRESS",
    "muscles": [
      "chest",
      "shoulders",
      "triceps"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "DUMBBELL FROG PRESS",
    "label": "DUMBBELL FROG PRESS",
    "muscles": [
      "glutes"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "DUMBBELL FRONT SQUAT",
    "label": "DUMBBELL FRONT SQUAT",
    "muscles": [
      "glutes",
      "quads",
      "shoulders",
      "abs"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "DUMBBELL GOBLET SQUAT",
    "label": "DUMBBELL GOBLET SQUAT",
    "muscles": [
      "quads"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "DUMBBELL HIP THRUST",
    "label": "DUMBBELL HIP THRUST",
    "muscles": [
      "glutes",
      "quads"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "DUMBBELL INCLINE CURL",
    "label": "DUMBBELL INCLINE CURL",
    "muscles": [
      "biceps"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "DUMBBELL INCLINE FLY",
    "label": "DUMBBELL INCLINE FLY",
    "muscles": [
      "chest"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "DUMBBELL LUNGES STANDING",
    "label": "DUMBBELL LUNGES STANDING",
    "muscles": [
      "quads",
      "glutes"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "DUMBBELL LUNGES WALKING",
    "label": "DUMBBELL LUNGES WALKING",
    "muscles": [
      "quads",
      "glutes"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "DUMBBELL PULLOVER",
    "label": "DUMBBELL PULLOVER",
    "muscles": [
      "back"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "DUMBBELL REAR DELT ROW",
    "label": "DUMBBELL REAR DELT ROW",
    "muscles": [
      "shoulders",
      "biceps",
      "back"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "DUMBBELL REAR LUNGE",
    "label": "DUMBBELL REAR LUNGE",
    "muscles": [
      "glutes",
      "quads",
      "calves"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "DUMBBELL ROMANIAN DEADLIFT",
    "label": "DUMBBELL ROMANIAN DEADLIFT",
    "muscles": [
      "hamstrings",
      "glutes"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "DUMBBELL SCAPTION",
    "label": "DUMBBELL SCAPTION",
    "muscles": [
      "back",
      "shoulders"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "DUMBBELL SHOULDER ROTATIONS",
    "label": "DUMBBELL SHOULDER ROTATIONS",
    "muscles": [
      "shoulders"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "DUMBBELL SIDE BEND",
    "label": "DUMBBELL SIDE BEND",
    "muscles": [
      "abs"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "DUMBBELL SIDE SQUAT",
    "label": "DUMBBELL SIDE SQUAT",
    "muscles": [
      "glutes",
      "quads",
      "hamstrings"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "DUMBBELL SINGLE-LEG HIP THRUST",
    "label": "DUMBBELL SINGLE-LEG HIP THRUST",
    "muscles": [
      "glutes",
      "hamstrings",
      "quads"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "DUMBBELL THRUSTER",
    "label": "DUMBBELL THRUSTER",
    "muscles": [
      "hamstrings",
      "glutes",
      "quads",
      "shoulders"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "DUMBBELL TRICEPS EXTENSION",
    "label": "DUMBBELL TRICEPS EXTENSION",
    "muscles": [
      "triceps",
      "shoulders",
      "chest"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "DUMBBELL UNDERHAND DEAD ROW",
    "label": "DUMBBELL UNDERHAND DEAD ROW",
    "muscles": [
      "biceps",
      "back"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "DUMBBELL UPRIGHT-ROW",
    "label": "DUMBBELL UPRIGHT-ROW",
    "muscles": [
      "shoulders",
      "biceps"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "DUMBBELL WIDE BICEP CURLS",
    "label": "DUMBBELL WIDE BICEP CURLS",
    "muscles": [
      "biceps"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "DUMBBELLS ON SCOTT MACHINE",
    "label": "DUMBBELLS ON SCOTT MACHINE",
    "muscles": [
      "biceps"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "DUMBELL TATE PRESS",
    "label": "DUMBELL TATE PRESS",
    "muscles": [
      "triceps",
      "shoulders",
      "chest"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "ELBOWS TUCKED DB BENCH PRESS",
    "label": "ELBOWS TUCKED DB BENCH PRESS",
    "muscles": [
      "triceps",
      "chest"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "ELEPHANT WALKS",
    "label": "ELEPHANT WALKS",
    "muscles": [
      "hamstrings",
      "calves"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "FACEPULL",
    "label": "FACEPULL",
    "muscles": [
      "back"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "FLAT MACHINE PRESS",
    "label": "FLAT MACHINE PRESS",
    "muscles": [
      "chest"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "FLOOR BENCH PRESS",
    "label": "FLOOR BENCH PRESS",
    "muscles": [
      "triceps",
      "shoulders"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "FLOOR DUMBBELL BENCH PRESS",
    "label": "FLOOR DUMBBELL BENCH PRESS",
    "muscles": [
      "chest",
      "triceps"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "FLOOR SKULL CRUSHER",
    "label": "FLOOR SKULL CRUSHER",
    "muscles": [
      "triceps"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "FLUTTER KICKS",
    "label": "FLUTTER KICKS",
    "muscles": [
      "abs"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "FLY WITH CABLE",
    "label": "FLY WITH CABLE",
    "muscles": [
      "chest"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "FLY WITH DUMBBELLS",
    "label": "FLY WITH DUMBBELLS",
    "muscles": [
      "chest"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "FLY WITH DUMBBELLS, DECLINE BENCH",
    "label": "FLY WITH DUMBBELLS, DECLINE BENCH",
    "muscles": [
      "chest"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "FROG STAND",
    "label": "FROG STAND",
    "muscles": [
      "shoulders",
      "biceps",
      "abs"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "FRONT PLATE RAISE",
    "label": "FRONT PLATE RAISE",
    "muscles": [
      "shoulders"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "FRONT PULL NARROW",
    "label": "FRONT PULL NARROW",
    "muscles": [
      "back",
      "biceps"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "FRONT PULL WIDE",
    "label": "FRONT PULL WIDE",
    "muscles": [
      "back",
      "shoulders",
      "biceps"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "FRONT RAISE (CABLE)",
    "label": "FRONT RAISE (CABLE)",
    "muscles": [
      "shoulders"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "FRONT RAISES",
    "label": "FRONT RAISES",
    "muscles": [
      "shoulders"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "FRONT RAISES WITH PLATES",
    "label": "FRONT RAISES WITH PLATES",
    "muscles": [
      "shoulders",
      "back"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "FRONT SQUATS",
    "label": "FRONT SQUATS",
    "muscles": [
      "glutes",
      "abs"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "FULL SIT OUTS",
    "label": "FULL SIT OUTS",
    "muscles": [
      "glutes",
      "abs"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "GLUTE BRIDGE",
    "label": "GLUTE BRIDGE",
    "muscles": [
      "glutes",
      "hamstrings"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "GLUTE BRIDGE SINGLE-ARM PRESS",
    "label": "GLUTE BRIDGE SINGLE-ARM PRESS",
    "muscles": [
      "chest",
      "shoulders",
      "biceps",
      "hamstrings",
      "glutes",
      "triceps"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "GLUTE DRIVE",
    "label": "GLUTE DRIVE",
    "muscles": [
      "glutes",
      "hamstrings",
      "quads"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "GLUTE KICKBACK (MACHINE)",
    "label": "GLUTE KICKBACK (MACHINE)",
    "muscles": [
      "glutes"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "GOOD MORNING",
    "label": "GOOD MORNING",
    "muscles": [
      "hamstrings"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "GOOD MORNINGS",
    "label": "GOOD MORNINGS",
    "muscles": [
      "hamstrings"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "HACK SQUATS",
    "label": "HACK SQUATS",
    "muscles": [
      "quads",
      "hamstrings",
      "calves",
      "glutes"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "HAMMER CURL",
    "label": "HAMMER CURL",
    "muscles": [
      "biceps",
      "shoulders",
      "abs",
      "forearms"
    ],
    "equipment": "dumbbell",
    "aliases": [
      "HC"
    ]
  },
  {
    "id": "HAMMER CURLS",
    "label": "HAMMER CURLS",
    "muscles": [
      "biceps"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "HAMMERCURLS ON CABLE",
    "label": "HAMMERCURLS ON CABLE",
    "muscles": [
      "biceps"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "HAMMERSTRENGTH DECLINE CHEST PRESS",
    "label": "HAMMERSTRENGTH DECLINE CHEST PRESS",
    "muscles": [
      "chest",
      "shoulders",
      "triceps"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "HAMSTRING CHOKES",
    "label": "HAMSTRING CHOKES",
    "muscles": [
      "hamstrings"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "HAMSTRING KICKS",
    "label": "HAMSTRING KICKS",
    "muscles": [
      "hamstrings",
      "glutes"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "HANGING LEG RAISES",
    "label": "HANGING LEG RAISES",
    "muscles": [
      "abs"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "HEEL TOUCHES",
    "label": "HEEL TOUCHES",
    "muscles": [
      "abs"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "HELMS ROW",
    "label": "HELMS ROW",
    "muscles": [
      "back"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "HIGH ROW",
    "label": "HIGH ROW",
    "muscles": [
      "back"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "HIGH-CABLE LATERAL RAISE",
    "label": "HIGH-CABLE LATERAL RAISE",
    "muscles": [
      "shoulders",
      "back"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "HIGH-INCLINE SMITH MACHINE PRESS",
    "label": "HIGH-INCLINE SMITH MACHINE PRESS",
    "muscles": [
      "shoulders",
      "chest",
      "triceps"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "HINDU PUSHUPS",
    "label": "HINDU PUSHUPS",
    "muscles": [
      "shoulders",
      "chest",
      "triceps"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "HINDU SQUATS",
    "label": "HINDU SQUATS",
    "muscles": [
      "quads",
      "glutes"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "HIP BRIDGE",
    "label": "HIP BRIDGE",
    "muscles": [
      "glutes",
      "abs"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "HIP HINGE",
    "label": "HIP HINGE",
    "muscles": [
      "hamstrings",
      "glutes",
      "calves",
      "quads",
      "abs"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "HIP THRUST",
    "label": "HIP THRUST",
    "muscles": [
      "glutes"
    ],
    "equipment": "barbell",
    "aliases": [
      "HT",
      "BARBELL HIP THRUST"
    ]
  },
  {
    "id": "HYPER Y W COMBO",
    "label": "HYPER Y W COMBO",
    "muscles": [
      "back"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "HYPEREXTENSIONS",
    "label": "HYPEREXTENSIONS",
    "muscles": [
      "back"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "ICE SCREAM MAKER",
    "label": "ICE SCREAM MAKER",
    "muscles": [
      "back",
      "abs"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "INCLINE BENCH PRESS - BARBELL",
    "label": "INCLINE BENCH PRESS - BARBELL",
    "muscles": [
      "chest",
      "shoulders",
      "triceps"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "INCLINE BENCH PRESS - DUMBBELL",
    "label": "INCLINE BENCH PRESS - DUMBBELL",
    "muscles": [
      "chest",
      "shoulders",
      "triceps"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "INCLINE BENCH REVERSE FLY",
    "label": "INCLINE BENCH REVERSE FLY",
    "muscles": [
      "shoulders",
      "back"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "INCLINE CHEST PRESS DB",
    "label": "INCLINE CHEST PRESS DB",
    "muscles": [
      "chest",
      "triceps"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "INCLINE CHEST-SUPPORTED DUMBBELL ROW",
    "label": "INCLINE CHEST-SUPPORTED DUMBBELL ROW",
    "muscles": [
      "biceps",
      "back"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "INCLINE CLOSE GRIP BARBELL BENCH PRESS",
    "label": "INCLINE CLOSE GRIP BARBELL BENCH PRESS",
    "muscles": [
      "triceps",
      "shoulders",
      "chest"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "INCLINE CRUNCHES",
    "label": "INCLINE CRUNCHES",
    "muscles": [
      "abs"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "INCLINE DB Y-RAISE",
    "label": "INCLINE DB Y-RAISE",
    "muscles": [
      "shoulders",
      "back"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "INCLINE DUMBBELL BENCH PRESS",
    "label": "INCLINE DUMBBELL BENCH PRESS",
    "muscles": [
      "chest",
      "shoulders"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "INCLINE DUMBBELL FLY",
    "label": "INCLINE DUMBBELL FLY",
    "muscles": [
      "chest"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "INCLINE DUMBBELL PRESS",
    "label": "INCLINE DUMBBELL PRESS",
    "muscles": [
      "chest",
      "shoulders",
      "triceps"
    ],
    "equipment": "dumbbell",
    "aliases": [
      "IDP"
    ]
  },
  {
    "id": "INCLINE DUMBBELL ROW",
    "label": "INCLINE DUMBBELL ROW",
    "muscles": [
      "back"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "INCLINE OHP DB",
    "label": "INCLINE OHP DB",
    "muscles": [
      "shoulders",
      "triceps"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "INCLINE PUSH UP",
    "label": "INCLINE PUSH UP",
    "muscles": [
      "chest",
      "hamstrings"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "INCLINE SHOULDER PRESS UP",
    "label": "INCLINE SHOULDER PRESS UP",
    "muscles": [
      "shoulders",
      "chest"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "INCLINE SKULL CRUSH",
    "label": "INCLINE SKULL CRUSH",
    "muscles": [
      "triceps"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "INCLINE SMITH PRESS",
    "label": "INCLINE SMITH PRESS",
    "muscles": [
      "chest"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "INVERTED LAT PULL DOWN",
    "label": "INVERTED LAT PULL DOWN",
    "muscles": [
      "back",
      "biceps",
      "abs"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "INVERTED ROWS",
    "label": "INVERTED ROWS",
    "muscles": [
      "biceps",
      "back",
      "chest",
      "abs"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "JM PRESS",
    "label": "JM PRESS",
    "muscles": [
      "triceps",
      "biceps",
      "chest"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "KETTLEBELL ONE LEGGED DEADLIFT",
    "label": "KETTLEBELL ONE LEGGED DEADLIFT",
    "muscles": [
      "glutes"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "KETTLEBELL SUMO DEADLIFT",
    "label": "KETTLEBELL SUMO DEADLIFT",
    "muscles": [
      "hamstrings",
      "glutes",
      "quads"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "KETTLEBELL SWINGS",
    "label": "KETTLEBELL SWINGS",
    "muscles": [
      "glutes",
      "hamstrings"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "KICKSTAND RDL",
    "label": "KICKSTAND RDL",
    "muscles": [
      "hamstrings"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "KNEE PUSH-UPS",
    "label": "KNEE PUSH-UPS",
    "muscles": [
      "shoulders",
      "chest",
      "triceps"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "KNEE RAISES",
    "label": "KNEE RAISES",
    "muscles": [
      "abs"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "KNEELING SUPERMAN",
    "label": "KNEELING SUPERMAN",
    "muscles": [
      "hamstrings",
      "back",
      "abs"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "KONG CURL",
    "label": "KONG CURL",
    "muscles": [
      "biceps"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "KREIS PRESS DB",
    "label": "KREIS PRESS DB",
    "muscles": [
      "shoulders",
      "biceps",
      "chest",
      "abs",
      "triceps"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "KROC ROW",
    "label": "KROC ROW",
    "muscles": [
      "back"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "LANDMINE PRESS",
    "label": "LANDMINE PRESS",
    "muscles": [
      "shoulders",
      "chest",
      "triceps"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "LANDMINE SQUAT TO PRESS",
    "label": "LANDMINE SQUAT TO PRESS",
    "muscles": [
      "shoulders",
      "glutes",
      "quads",
      "hamstrings",
      "abs"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "LARSEN PRESS",
    "label": "LARSEN PRESS",
    "muscles": [
      "chest",
      "triceps"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "LAT PULL DB",
    "label": "LAT PULL DB",
    "muscles": [
      "back",
      "glutes"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "LAT PULL DOWN",
    "label": "LAT PULL DOWN",
    "muscles": [
      "back",
      "shoulders",
      "biceps"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "LAT PULL DOWN (LEANING BACK)",
    "label": "LAT PULL DOWN (LEANING BACK)",
    "muscles": [
      "back"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "LAT PULL DOWN (STRAIGHT BACK)",
    "label": "LAT PULL DOWN (STRAIGHT BACK)",
    "muscles": [
      "back"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "LAT PULLDOWN - CROSS BODY SINGLE ARM",
    "label": "LAT PULLDOWN - CROSS BODY SINGLE ARM",
    "muscles": [
      "back"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "LAT PULLDOWN (WIDE GRIP)",
    "label": "LAT PULLDOWN (WIDE GRIP)",
    "muscles": [
      "back"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "LATERAL RAISES",
    "label": "LATERAL RAISES",
    "muscles": [
      "shoulders"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "LATERAL ROWS ON CABLE, ONE ARMED",
    "label": "LATERAL ROWS ON CABLE, ONE ARMED",
    "muscles": [
      "shoulders"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "LATERAL-TO-FRONT RAISES",
    "label": "LATERAL-TO-FRONT RAISES",
    "muscles": [
      "shoulders",
      "back"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "LEG CURL",
    "label": "LEG CURL",
    "muscles": [
      "hamstrings",
      "glutes"
    ],
    "equipment": "machine",
    "aliases": [
      "LC",
      "HAMSTRING CURL"
    ]
  },
  {
    "id": "LEG CURLS (LAYING)",
    "label": "LEG CURLS (LAYING)",
    "muscles": [
      "hamstrings"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "LEG CURLS (SITTING)",
    "label": "LEG CURLS (SITTING)",
    "muscles": [
      "hamstrings"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "LEG CURLS (STANDING)",
    "label": "LEG CURLS (STANDING)",
    "muscles": [
      "hamstrings"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "LEG EXTENSION",
    "label": "LEG EXTENSION",
    "muscles": [
      "quads"
    ],
    "equipment": "machine",
    "aliases": [
      "LE"
    ]
  },
  {
    "id": "LEG PRESS",
    "label": "LEG PRESS",
    "muscles": [
      "hamstrings",
      "calves",
      "glutes",
      "quads"
    ],
    "equipment": "machine",
    "aliases": [
      "LP"
    ]
  },
  {
    "id": "LEG PRESS ON HACKENSCHMIDT MACHINE",
    "label": "LEG PRESS ON HACKENSCHMIDT MACHINE",
    "muscles": [
      "quads"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "LEG PRESS TOE PRESS",
    "label": "LEG PRESS TOE PRESS",
    "muscles": [
      "calves"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "LEG PRESSES (NARROW)",
    "label": "LEG PRESSES (NARROW)",
    "muscles": [
      "quads",
      "glutes"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "LEG PRESSES (WIDE)",
    "label": "LEG PRESSES (WIDE)",
    "muscles": [
      "quads",
      "glutes"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "LEG RAISE",
    "label": "LEG RAISE",
    "muscles": [
      "abs"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "LEG RAISES PULL UP BAR",
    "label": "LEG RAISES PULL UP BAR",
    "muscles": [
      "abs",
      "quads"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "LEG RAISES, LYING",
    "label": "LEG RAISES, LYING",
    "muscles": [
      "abs"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "LEG RAISES, STANDING",
    "label": "LEG RAISES, STANDING",
    "muscles": [
      "abs"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "LEG WHEEL",
    "label": "LEG WHEEL",
    "muscles": [
      "abs"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "LEGEND INCLINE BENCH PRESS",
    "label": "LEGEND INCLINE BENCH PRESS",
    "muscles": [
      "chest",
      "shoulders",
      "triceps"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "LEVERAGE MACHINE CHEST PRESS",
    "label": "LEVERAGE MACHINE CHEST PRESS",
    "muscles": [
      "chest"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "LEVERAGE MACHINE ISO ROW",
    "label": "LEVERAGE MACHINE ISO ROW",
    "muscles": [
      "back"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "LEVITATION CRUNCH",
    "label": "LEVITATION CRUNCH",
    "muscles": [
      "abs"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "LONG-PULLEY (LOW ROW)",
    "label": "LONG-PULLEY (LOW ROW)",
    "muscles": [
      "back",
      "biceps"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "LONG-PULLEY, NARROW",
    "label": "LONG-PULLEY, NARROW",
    "muscles": [
      "back",
      "biceps"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "LOW BOX SQUAT - WIDE STANCE",
    "label": "LOW BOX SQUAT - WIDE STANCE",
    "muscles": [
      "glutes",
      "quads"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "LOW PULLEY CABLE FLY",
    "label": "LOW PULLEY CABLE FLY",
    "muscles": [
      "chest",
      "shoulders"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "LYING BICEP CURL",
    "label": "LYING BICEP CURL",
    "muscles": [
      "biceps"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "LYING DUMBBELL CURLS",
    "label": "LYING DUMBBELL CURLS",
    "muscles": [
      "biceps"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "LYING DUMBBELL ROW SS SEATED SHRUG",
    "label": "LYING DUMBBELL ROW SS SEATED SHRUG",
    "muscles": [
      "back"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "LYING LEG RAISE",
    "label": "LYING LEG RAISE",
    "muscles": [
      "abs"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "LYING TRICEPS EXTENSIONS",
    "label": "LYING TRICEPS EXTENSIONS",
    "muscles": [
      "triceps"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "LYING TRICEPS KICKBACK",
    "label": "LYING TRICEPS KICKBACK",
    "muscles": [
      "triceps"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "MACHINE CHEST FLY",
    "label": "MACHINE CHEST FLY",
    "muscles": [
      "chest"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "MACHINE CHEST PRESS",
    "label": "MACHINE CHEST PRESS",
    "muscles": [
      "chest",
      "shoulders",
      "biceps",
      "triceps"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "MACHINE CHEST PRESS EXERCISE",
    "label": "MACHINE CHEST PRESS EXERCISE",
    "muscles": [
      "chest",
      "triceps"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "MACHINE HIP ABDUCTION",
    "label": "MACHINE HIP ABDUCTION",
    "muscles": [
      "glutes"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "MACHINE LATERAL WISE",
    "label": "MACHINE LATERAL WISE",
    "muscles": [
      "shoulders"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "MACHINE SIDE LATERAL RAISES",
    "label": "MACHINE SIDE LATERAL RAISES",
    "muscles": [
      "shoulders"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "MEADOWS ROW",
    "label": "MEADOWS ROW",
    "muscles": [
      "back",
      "biceps",
      "abs"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "MODIFIED PULLDOWN",
    "label": "MODIFIED PULLDOWN",
    "muscles": [
      "back"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "NECK EXTENSION",
    "label": "NECK EXTENSION",
    "muscles": [
      "biceps"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "NEGATIVE CRUNCHES",
    "label": "NEGATIVE CRUNCHES",
    "muscles": [
      "abs"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "NEUTRAL GRIP LAT PULLDOWN",
    "label": "NEUTRAL GRIP LAT PULLDOWN",
    "muscles": [
      "back"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "NO LEG DRIVE DUMBBELL CHEST PRESS",
    "label": "NO LEG DRIVE DUMBBELL CHEST PRESS",
    "muscles": [
      "chest",
      "shoulders",
      "triceps"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "NORDIC CURL",
    "label": "NORDIC CURL",
    "muscles": [
      "hamstrings",
      "glutes"
    ],
    "equipment": "bodyweight",
    "aliases": [
      "NORDIC"
    ]
  },
  {
    "id": "OMNI CABLE CROSS-OVER",
    "label": "OMNI CABLE CROSS-OVER",
    "muscles": [
      "chest"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "ONE ARM OVERHEAD CABLE TRICEP EXTENSION",
    "label": "ONE ARM OVERHEAD CABLE TRICEP EXTENSION",
    "muscles": [
      "triceps"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "ONE ARMED PUSH-UPS",
    "label": "ONE ARMED PUSH-UPS",
    "muscles": [
      "chest",
      "triceps",
      "shoulders",
      "abs"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "ONE-ARM HEAVY ROW",
    "label": "ONE-ARM HEAVY ROW",
    "muscles": [
      "back"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "ONE-HANDED KETTLEBELL CURLS",
    "label": "ONE-HANDED KETTLEBELL CURLS",
    "muscles": [
      "biceps"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "OVERHAND CABLE CURL",
    "label": "OVERHAND CABLE CURL",
    "muscles": [
      "biceps"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "OVERHEAD BARBELL PRESS",
    "label": "OVERHEAD BARBELL PRESS",
    "muscles": [
      "shoulders"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "OVERHEAD CABLE TRICEP EXTENSION",
    "label": "OVERHEAD CABLE TRICEP EXTENSION",
    "muscles": [
      "triceps"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "OVERHEAD PRESS",
    "label": "OVERHEAD PRESS",
    "muscles": [
      "shoulders"
    ],
    "equipment": "barbell",
    "aliases": [
      "OHP",
      "STRICT PRESS"
    ]
  },
  {
    "id": "OVERHEAD TRICEPS EXTENSION",
    "label": "OVERHEAD TRICEPS EXTENSION",
    "muscles": [
      "back"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "PALLOF PRESS",
    "label": "PALLOF PRESS",
    "muscles": [
      "shoulders",
      "glutes",
      "abs",
      "back",
      "chest",
      "triceps"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "PATADAS TRASERAS",
    "label": "PATADAS TRASERAS",
    "muscles": [
      "triceps"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "PAUSE BENCH",
    "label": "PAUSE BENCH",
    "muscles": [
      "chest",
      "triceps"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "PAUSE HACK SQUATS",
    "label": "PAUSE HACK SQUATS",
    "muscles": [
      "quads",
      "hamstrings",
      "calves",
      "glutes"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "PEC DECK",
    "label": "PEC DECK",
    "muscles": [
      "chest"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "PENDELAY ROWS",
    "label": "PENDELAY ROWS",
    "muscles": [
      "back",
      "biceps",
      "triceps"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "PENDULUM SQUAT",
    "label": "PENDULUM SQUAT",
    "muscles": [
      "quads",
      "hamstrings",
      "glutes"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "PERPENDICULAR UNILATERAL LANDMINE ROW",
    "label": "PERPENDICULAR UNILATERAL LANDMINE ROW",
    "muscles": [
      "shoulders",
      "back"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "PIKE PUSH UPS",
    "label": "PIKE PUSH UPS",
    "muscles": [
      "chest",
      "triceps"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "PIN BENCH PRESS BB",
    "label": "PIN BENCH PRESS BB",
    "muscles": [
      "chest",
      "triceps"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "PIN OHP",
    "label": "PIN OHP",
    "muscles": [
      "shoulders",
      "triceps"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "PIN SQUAT",
    "label": "PIN SQUAT",
    "muscles": [
      "hamstrings",
      "glutes",
      "quads",
      "abs"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "PLATE TWIST",
    "label": "PLATE TWIST",
    "muscles": [
      "abs"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "PREACHER CURL - EXTERNALLY ROTATED",
    "label": "PREACHER CURL - EXTERNALLY ROTATED",
    "muscles": [
      "biceps"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "PREACHER CURL - INTERNALLY ROTATED",
    "label": "PREACHER CURL - INTERNALLY ROTATED",
    "muscles": [
      "biceps"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "PREACHER CURLS",
    "label": "PREACHER CURLS",
    "muscles": [
      "biceps"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "PRONE SCAPULAR RETRACTION - ARMS AT SIDE",
    "label": "PRONE SCAPULAR RETRACTION - ARMS AT SIDE",
    "muscles": [
      "back"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "PULL UPS ON MACHINE",
    "label": "PULL UPS ON MACHINE",
    "muscles": [
      "back",
      "shoulders",
      "biceps"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "PULL-UPS",
    "label": "PULL-UPS",
    "muscles": [
      "back",
      "shoulders",
      "biceps"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "PULL-UPS (NEUTRAL GRIP)",
    "label": "PULL-UPS (NEUTRAL GRIP)",
    "muscles": [
      "back"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "PULL-UPS (WIDE GRIP)",
    "label": "PULL-UPS (WIDE GRIP)",
    "muscles": [
      "back"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "PULLOVER",
    "label": "PULLOVER",
    "muscles": [
      "chest",
      "back"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "PULLOVER MACHINE",
    "label": "PULLOVER MACHINE",
    "muscles": [
      "back",
      "chest",
      "triceps"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "PUNCHES",
    "label": "PUNCHES",
    "muscles": [
      "shoulders",
      "triceps"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "PUSH OHP",
    "label": "PUSH OHP",
    "muscles": [
      "shoulders",
      "glutes",
      "quads",
      "triceps"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "PUSH PRESS",
    "label": "PUSH PRESS",
    "muscles": [
      "back",
      "glutes"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "PUSH-UP",
    "label": "PUSH-UP",
    "muscles": [
      "chest",
      "shoulders",
      "abs",
      "triceps"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "PUSH-UPS",
    "label": "PUSH-UPS",
    "muscles": [
      "chest",
      "shoulders",
      "abs",
      "triceps"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "PUSH-UPS | DECLINE",
    "label": "PUSH-UPS | DECLINE",
    "muscles": [
      "chest",
      "shoulders",
      "triceps"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "PUSH-UPS | INCLINE",
    "label": "PUSH-UPS | INCLINE",
    "muscles": [
      "chest",
      "triceps"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "PUSH-UPS | PARALLETTES",
    "label": "PUSH-UPS | PARALLETTES",
    "muscles": [
      "chest",
      "shoulders",
      "triceps"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "QUADRIPED ARM AND LEG RAISE",
    "label": "QUADRIPED ARM AND LEG RAISE",
    "muscles": [
      "shoulders",
      "glutes",
      "back"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "RACK DEADLIFT",
    "label": "RACK DEADLIFT",
    "muscles": [
      "glutes",
      "biceps"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "REACH UPS",
    "label": "REACH UPS",
    "muscles": [
      "abs"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "REAR DELT RAISE",
    "label": "REAR DELT RAISE",
    "muscles": [
      "shoulders",
      "back"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "RENEGADE ROW",
    "label": "RENEGADE ROW",
    "muscles": [
      "back"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "REVERSE BAR CURL",
    "label": "REVERSE BAR CURL",
    "muscles": [
      "biceps"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "REVERSE CABLE FLYE",
    "label": "REVERSE CABLE FLYE",
    "muscles": [
      "shoulders",
      "back"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "REVERSE CRUNCH",
    "label": "REVERSE CRUNCH",
    "muscles": [
      "abs"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "REVERSE CURL",
    "label": "REVERSE CURL",
    "muscles": [
      "biceps"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "REVERSE EZ BAR CABLE CURLS",
    "label": "REVERSE EZ BAR CABLE CURLS",
    "muscles": [
      "biceps"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "REVERSE FLY STANDING",
    "label": "REVERSE FLY STANDING",
    "muscles": [
      "shoulders",
      "back"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "REVERSE GRIP BARBELL CURLS",
    "label": "REVERSE GRIP BARBELL CURLS",
    "muscles": [
      "biceps"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "REVERSE GRIP BENCH PRESS",
    "label": "REVERSE GRIP BENCH PRESS",
    "muscles": [
      "chest",
      "triceps",
      "shoulders"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "REVERSE HYPEREXTENSION",
    "label": "REVERSE HYPEREXTENSION",
    "muscles": [
      "hamstrings",
      "glutes"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "REVERSE NORDIC CURL",
    "label": "REVERSE NORDIC CURL",
    "muscles": [
      "quads",
      "glutes",
      "abs"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "REVERSE PREACHER CURL (CLOSE GRIP)",
    "label": "REVERSE PREACHER CURL (CLOSE GRIP)",
    "muscles": [
      "biceps"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "REVERSE SNOW ANGEL",
    "label": "REVERSE SNOW ANGEL",
    "muscles": [
      "back",
      "shoulders",
      "hamstrings",
      "glutes",
      "abs"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "REVERSE WOOD CHOPS",
    "label": "REVERSE WOOD CHOPS",
    "muscles": [
      "glutes",
      "back",
      "shoulders",
      "biceps",
      "abs",
      "quads"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "RING DIPS",
    "label": "RING DIPS",
    "muscles": [
      "triceps"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "ROCKING TRICEPS PUSHDOWN",
    "label": "ROCKING TRICEPS PUSHDOWN",
    "muscles": [
      "triceps"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "ROLL DOWN",
    "label": "ROLL DOWN",
    "muscles": [
      "hamstrings"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "ROMANIAN DEADLIFT",
    "label": "ROMANIAN DEADLIFT",
    "muscles": [
      "glutes",
      "hamstrings"
    ],
    "equipment": "dumbbell",
    "aliases": [
      "RDL"
    ]
  },
  {
    "id": "ROMANIAN DEADLIFT, SINGLE LEG",
    "label": "ROMANIAN DEADLIFT, SINGLE LEG",
    "muscles": [
      "hamstrings"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "ROPE PULLOVER/ROW",
    "label": "ROPE PULLOVER/ROW",
    "muscles": [
      "back"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "ROTARY TORSO MACHINE",
    "label": "ROTARY TORSO MACHINE",
    "muscles": [
      "abs"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "ROW",
    "label": "ROW",
    "muscles": [
      "back",
      "quads"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "ROWING SEATED, NARROW GRIP",
    "label": "ROWING SEATED, NARROW GRIP",
    "muscles": [
      "back"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "ROWING, LYING ON BENCH",
    "label": "ROWING, LYING ON BENCH",
    "muscles": [
      "back"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "ROWING, T-BAR",
    "label": "ROWING, T-BAR",
    "muscles": [
      "back",
      "shoulders",
      "biceps"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "SCAPULA PULLS",
    "label": "SCAPULA PULLS",
    "muscles": [
      "back"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "SCHOULDER RAISE (DUMBBELL)",
    "label": "SCHOULDER RAISE (DUMBBELL)",
    "muscles": [
      "shoulders"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "SCISSORS",
    "label": "SCISSORS",
    "muscles": [
      "abs"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "SEATED BENCH PRESS",
    "label": "SEATED BENCH PRESS",
    "muscles": [
      "chest"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "SEATED CABLE CHEST FLY",
    "label": "SEATED CABLE CHEST FLY",
    "muscles": [
      "chest"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "SEATED CABLE MID TRAP SHRUG",
    "label": "SEATED CABLE MID TRAP SHRUG",
    "muscles": [
      "back"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "SEATED CABLE ROWS",
    "label": "SEATED CABLE ROWS",
    "muscles": [
      "back"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "SEATED CORKSCREW",
    "label": "SEATED CORKSCREW",
    "muscles": [
      "abs"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "SEATED DUMBBELL CALF RAISE",
    "label": "SEATED DUMBBELL CALF RAISE",
    "muscles": [
      "calves"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "SEATED DUMBBELL CURLS",
    "label": "SEATED DUMBBELL CURLS",
    "muscles": [
      "biceps"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "SEATED DUMBBELL SIDE LATERAL",
    "label": "SEATED DUMBBELL SIDE LATERAL",
    "muscles": [
      "shoulders"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "SEATED FIGURE FOUR",
    "label": "SEATED FIGURE FOUR",
    "muscles": [
      "glutes"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "SEATED HIP ABDUCTION",
    "label": "SEATED HIP ABDUCTION",
    "muscles": [
      "glutes"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "SEATED HIP ADDUCTION",
    "label": "SEATED HIP ADDUCTION",
    "muscles": [
      "glutes"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "SEATED KNEE TUCK",
    "label": "SEATED KNEE TUCK",
    "muscles": [
      "abs"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "SEATED MACHINE ROW",
    "label": "SEATED MACHINE ROW",
    "muscles": [
      "back"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "SEATED PANCAKE GOOD MORNING",
    "label": "SEATED PANCAKE GOOD MORNING",
    "muscles": [
      "glutes"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "SEATED REAR DELT RISE",
    "label": "SEATED REAR DELT RISE",
    "muscles": [
      "back"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "SEATED ROW (MACHINE)",
    "label": "SEATED ROW (MACHINE)",
    "muscles": [
      "back",
      "shoulders"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "SEATED TRICEPS PRESS",
    "label": "SEATED TRICEPS PRESS",
    "muscles": [
      "triceps"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "SEATED V-GRIP ROW",
    "label": "SEATED V-GRIP ROW",
    "muscles": [
      "back",
      "shoulders",
      "biceps",
      "abs"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "SEATED W CURL",
    "label": "SEATED W CURL",
    "muscles": [
      "biceps"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "SHOTGUN ROW",
    "label": "SHOTGUN ROW",
    "muscles": [
      "back"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "SHOULDER DUMBBELL PENDULAR EXERCISE",
    "label": "SHOULDER DUMBBELL PENDULAR EXERCISE",
    "muscles": [
      "shoulders",
      "back",
      "chest"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "SHOULDER EXTERNAL ROTATION (CABLE)",
    "label": "SHOULDER EXTERNAL ROTATION (CABLE)",
    "muscles": [
      "shoulders"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "SHOULDER EXTERNAL ROTATION WITH DUMBBELL",
    "label": "SHOULDER EXTERNAL ROTATION WITH DUMBBELL",
    "muscles": [
      "shoulders",
      "biceps",
      "back"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "SHOULDER INTERNAL ROTATION (CABLE)",
    "label": "SHOULDER INTERNAL ROTATION (CABLE)",
    "muscles": [
      "shoulders"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "SHOULDER PRESS (DUMBBELL)",
    "label": "SHOULDER PRESS (DUMBBELL)",
    "muscles": [
      "shoulders"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "SHOULDER PRESS, BARBELL",
    "label": "SHOULDER PRESS, BARBELL",
    "muscles": [
      "shoulders"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "SHOULDER PRESS, DUMBBELLS",
    "label": "SHOULDER PRESS, DUMBBELLS",
    "muscles": [
      "shoulders"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "SHOULDER PRESS, ON MACHINE",
    "label": "SHOULDER PRESS, ON MACHINE",
    "muscles": [
      "shoulders",
      "triceps"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "SHOULDER PRESS, ON MULTI PRESS",
    "label": "SHOULDER PRESS, ON MULTI PRESS",
    "muscles": [
      "shoulders"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "SHOULDER RAISE SIDE AND FRONT DB",
    "label": "SHOULDER RAISE SIDE AND FRONT DB",
    "muscles": [
      "shoulders"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "SHOULDER SHRUG",
    "label": "SHOULDER SHRUG",
    "muscles": [
      "back"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "SHRUGS ON MULTIPRESS",
    "label": "SHRUGS ON MULTIPRESS",
    "muscles": [
      "shoulders",
      "triceps"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "SHRUGS, BARBELLS",
    "label": "SHRUGS, BARBELLS",
    "muscles": [
      "shoulders"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "SHRUGS, DUMBBELLS",
    "label": "SHRUGS, DUMBBELLS",
    "muscles": [
      "shoulders"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "SIDE BENDS ON MACHINE",
    "label": "SIDE BENDS ON MACHINE",
    "muscles": [
      "abs"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "SIDE CRUNCH",
    "label": "SIDE CRUNCH",
    "muscles": [
      "abs"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "SIDE DUMBBELL TRUNK FLEXION",
    "label": "SIDE DUMBBELL TRUNK FLEXION",
    "muscles": [
      "abs"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "SIDE LATERAL RAISE - BACK (CABLE)",
    "label": "SIDE LATERAL RAISE - BACK (CABLE)",
    "muscles": [
      "shoulders"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "SIDE LATERAL RAISE - FRONT (CABLE)",
    "label": "SIDE LATERAL RAISE - FRONT (CABLE)",
    "muscles": [
      "shoulders"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "SIDE LATERAL RAISE (CABLE)",
    "label": "SIDE LATERAL RAISE (CABLE)",
    "muscles": [
      "back"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "SIDE STRAIGHT-ARM PULLDOWN (CABLE)",
    "label": "SIDE STRAIGHT-ARM PULLDOWN (CABLE)",
    "muscles": [
      "back"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "SIDE TO SIDE PUSH UPS",
    "label": "SIDE TO SIDE PUSH UPS",
    "muscles": [
      "shoulders",
      "abs",
      "chest",
      "triceps"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "SIDE-LAYING INTERIOR ROTATION",
    "label": "SIDE-LAYING INTERIOR ROTATION",
    "muscles": [
      "back"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "SINGLE ARM ROW",
    "label": "SINGLE ARM ROW",
    "muscles": [
      "back"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "SINGLE LEG EXTENSION",
    "label": "SINGLE LEG EXTENSION",
    "muscles": [
      "quads"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "SINGLE LEG GLUTE BRIDGE",
    "label": "SINGLE LEG GLUTE BRIDGE",
    "muscles": [
      "glutes"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "SINGLE LEG RDL",
    "label": "SINGLE LEG RDL",
    "muscles": [
      "hamstrings",
      "glutes"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "SINGLE-ARM PREACHER CURL",
    "label": "SINGLE-ARM PREACHER CURL",
    "muscles": [
      "biceps"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "SINGLE-LEG DEADLIFT WITH DUMBBELL",
    "label": "SINGLE-LEG DEADLIFT WITH DUMBBELL",
    "muscles": [
      "hamstrings",
      "glutes"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "SINGLE-LEG LUNGE WITH KETTLEBELL:",
    "label": "SINGLE-LEG LUNGE WITH KETTLEBELL:",
    "muscles": [
      "calves",
      "glutes",
      "quads"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "SINGLE-LEG SIDE GLUTE PRESS",
    "label": "SINGLE-LEG SIDE GLUTE PRESS",
    "muscles": [
      "calves",
      "glutes",
      "quads"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "SIT & REACH",
    "label": "SIT & REACH",
    "muscles": [
      "hamstrings"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "SIT UP ELBOW THRUST",
    "label": "SIT UP ELBOW THRUST",
    "muscles": [
      "abs"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "SIT-UPS",
    "label": "SIT-UPS",
    "muscles": [
      "abs"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "SITTING CALF RAISES",
    "label": "SITTING CALF RAISES",
    "muscles": [
      "calves"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "SKULLCRUSHER DUMBBELLS",
    "label": "SKULLCRUSHER DUMBBELLS",
    "muscles": [
      "triceps"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "SKULLCRUSHER SZ-BAR",
    "label": "SKULLCRUSHER SZ-BAR",
    "muscles": [
      "triceps"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "SLIDING LATERAL LUNGE",
    "label": "SLIDING LATERAL LUNGE",
    "muscles": [
      "hamstrings",
      "glutes",
      "quads",
      "calves",
      "abs"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "SMITH MACHINE CLOSE-GRIP BENCH PRESS",
    "label": "SMITH MACHINE CLOSE-GRIP BENCH PRESS",
    "muscles": [
      "triceps",
      "chest"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "SMITH MACHINE SLIGHT INCLINE PRESS",
    "label": "SMITH MACHINE SLIGHT INCLINE PRESS",
    "muscles": [
      "chest"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "SMITH MACHINE SPLIT SQUAT",
    "label": "SMITH MACHINE SPLIT SQUAT",
    "muscles": [
      "hamstrings",
      "quads"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "SMITH MACHINE SQUAT",
    "label": "SMITH MACHINE SQUAT",
    "muscles": [
      "glutes",
      "quads"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "SMITH PRESS",
    "label": "SMITH PRESS",
    "muscles": [
      "shoulders"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "SNACH",
    "label": "SNACH",
    "muscles": [
      "shoulders"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "SPHINX",
    "label": "SPHINX",
    "muscles": [
      "abs"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "SPIDER CURL",
    "label": "SPIDER CURL",
    "muscles": [
      "biceps"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "SPLINTER SIT-UPS",
    "label": "SPLINTER SIT-UPS",
    "muscles": [
      "abs"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "SQUATS",
    "label": "SQUATS",
    "muscles": [
      "quads",
      "glutes"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "SQUATS ON MULTIPRESS",
    "label": "SQUATS ON MULTIPRESS",
    "muscles": [
      "quads",
      "glutes"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "STANDING BICEP CURL",
    "label": "STANDING BICEP CURL",
    "muscles": [
      "biceps"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "STANDING CALF RAISES",
    "label": "STANDING CALF RAISES",
    "muscles": [
      "calves"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "STANDING PANCAKE",
    "label": "STANDING PANCAKE",
    "muscles": [
      "hamstrings"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "STANDING PANCAKE GOOD MORNING",
    "label": "STANDING PANCAKE GOOD MORNING",
    "muscles": [
      "hamstrings"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "STANDING SIDE CRUNCHES",
    "label": "STANDING SIDE CRUNCHES",
    "muscles": [
      "abs"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "STIFF-LEGGED DEADLIFTS",
    "label": "STIFF-LEGGED DEADLIFTS",
    "muscles": [
      "hamstrings",
      "glutes"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "STRAIGHT BAR CABLE CURLS",
    "label": "STRAIGHT BAR CABLE CURLS",
    "muscles": [
      "biceps"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "STRAIGHT BAR CABLE FRONT RAISE",
    "label": "STRAIGHT BAR CABLE FRONT RAISE",
    "muscles": [
      "shoulders"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "STRAIGHT-ARM PULL DOWN (BAR ATTACHMENT)",
    "label": "STRAIGHT-ARM PULL DOWN (BAR ATTACHMENT)",
    "muscles": [
      "back",
      "triceps"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "STRAIGHT-ARM PULL DOWN (ROPE ATTACHMENT)",
    "label": "STRAIGHT-ARM PULL DOWN (ROPE ATTACHMENT)",
    "muscles": [
      "back",
      "triceps"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "STRAIGHT-ARM PULLDOWN (CABLE)",
    "label": "STRAIGHT-ARM PULLDOWN (CABLE)",
    "muscles": [
      "back"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "SUMO DEADLIFT",
    "label": "SUMO DEADLIFT",
    "muscles": [
      "quads"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "SUMO SQUATS",
    "label": "SUMO SQUATS",
    "muscles": [
      "glutes",
      "quads"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "SUPERMAN",
    "label": "SUPERMAN",
    "muscles": [
      "glutes",
      "back"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "SUPINE HIP ABDUCTION",
    "label": "SUPINE HIP ABDUCTION",
    "muscles": [
      "glutes",
      "quads"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "SUPINE PRESS",
    "label": "SUPINE PRESS",
    "muscles": [
      "back"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "T-BAR ROW",
    "label": "T-BAR ROW",
    "muscles": [
      "back"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "THRUSTER",
    "label": "THRUSTER",
    "muscles": [
      "shoulders",
      "back"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "TOE TAPS",
    "label": "TOE TAPS",
    "muscles": [
      "abs"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "TOE TOUCH",
    "label": "TOE TOUCH",
    "muscles": [
      "hamstrings",
      "glutes",
      "calves"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "TORSO TWIST",
    "label": "TORSO TWIST",
    "muscles": [
      "abs"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "TOWEL SUPERMAN",
    "label": "TOWEL SUPERMAN",
    "muscles": [
      "back",
      "shoulders"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "TRAP BAR SQUAT",
    "label": "TRAP BAR SQUAT",
    "muscles": [
      "quads",
      "hamstrings"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "TRAP PRESS",
    "label": "TRAP PRESS",
    "muscles": [
      "back"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "TRAP-3 RAISE",
    "label": "TRAP-3 RAISE",
    "muscles": [
      "back"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "TRICEP DUMBBELL KICKBACK",
    "label": "TRICEP DUMBBELL KICKBACK",
    "muscles": [
      "triceps"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "TRICEP PUSHDOWN ON CABLE",
    "label": "TRICEP PUSHDOWN ON CABLE",
    "muscles": [
      "triceps"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "TRICEP ROPE PUSHDOWNS",
    "label": "TRICEP ROPE PUSHDOWNS",
    "muscles": [
      "triceps",
      "back"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "TRICEPS DIPS (ASSISTED)",
    "label": "TRICEPS DIPS (ASSISTED)",
    "muscles": [
      "triceps",
      "chest"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "TRICEPS EXTENSIONS ON CABLE",
    "label": "TRICEPS EXTENSIONS ON CABLE",
    "muscles": [
      "triceps"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "TRICEPS EXTENSIONS ON CABLE WITH BAR",
    "label": "TRICEPS EXTENSIONS ON CABLE WITH BAR",
    "muscles": [
      "triceps"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "TRICEPS ON MACHINE",
    "label": "TRICEPS ON MACHINE",
    "muscles": [
      "triceps"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "TRICEPS OVERHEAD (DUMBBELL)",
    "label": "TRICEPS OVERHEAD (DUMBBELL)",
    "muscles": [
      "triceps"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "TRICEPS PUSHDOWN",
    "label": "TRICEPS PUSHDOWN",
    "muscles": [
      "triceps"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "TRUNK ROTATION WITH CABLE",
    "label": "TRUNK ROTATION WITH CABLE",
    "muscles": [
      "abs",
      "back"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "TYPEWRITER PULL-UPS",
    "label": "TYPEWRITER PULL-UPS",
    "muscles": [
      "biceps",
      "back"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "UNDERHAND LAT PULL DOWN",
    "label": "UNDERHAND LAT PULL DOWN",
    "muscles": [
      "back",
      "biceps"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "UNILATERAL CABLE ROW",
    "label": "UNILATERAL CABLE ROW",
    "muscles": [
      "back"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "UNILATERAL CROSS BODY CABLE PULL DOWN",
    "label": "UNILATERAL CROSS BODY CABLE PULL DOWN",
    "muscles": [
      "shoulders"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "UNILATERAL HIP THRUST",
    "label": "UNILATERAL HIP THRUST",
    "muscles": [
      "glutes",
      "abs"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "UNILATERAL LUNGES",
    "label": "UNILATERAL LUNGES",
    "muscles": [
      "glutes",
      "quads",
      "hamstrings"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "UPRIGHT ROW W/ DUMBBELLS",
    "label": "UPRIGHT ROW W/ DUMBBELLS",
    "muscles": [
      "shoulders",
      "back",
      "biceps"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "UPRIGHT ROW, ON MULTI PRESS",
    "label": "UPRIGHT ROW, ON MULTI PRESS",
    "muscles": [
      "shoulders",
      "back",
      "biceps"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "UPRIGHT ROW, SZ-BAR",
    "label": "UPRIGHT ROW, SZ-BAR",
    "muscles": [
      "shoulders",
      "back",
      "biceps"
    ],
    "equipment": "barbell",
    "aliases": []
  },
  {
    "id": "VPUSHUP",
    "label": "VPUSHUP",
    "muscles": [
      "chest",
      "quads",
      "abs",
      "triceps"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "W-RAISE",
    "label": "W-RAISE",
    "muscles": [
      "abs"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "WALKING BRIDGE",
    "label": "WALKING BRIDGE",
    "muscles": [
      "abs",
      "shoulders",
      "biceps",
      "glutes",
      "back"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "WALKING LUNGES",
    "label": "WALKING LUNGES",
    "muscles": [
      "quads",
      "glutes"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "WALL ANGELS",
    "label": "WALL ANGELS",
    "muscles": [
      "back",
      "shoulders"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "WALL DRILLS",
    "label": "WALL DRILLS",
    "muscles": [
      "quads",
      "calves"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "WALL PUSHUP",
    "label": "WALL PUSHUP",
    "muscles": [
      "shoulders",
      "chest",
      "triceps",
      "glutes",
      "abs",
      "back"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "WALL SLIDES",
    "label": "WALL SLIDES",
    "muscles": [
      "biceps",
      "hamstrings",
      "chest",
      "back",
      "triceps"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "WALL SQUAT",
    "label": "WALL SQUAT",
    "muscles": [
      "hamstrings",
      "quads"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "WEIGHTED CRUNCH",
    "label": "WEIGHTED CRUNCH",
    "muscles": [
      "abs"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "WEIGHTED PUSH-UPS",
    "label": "WEIGHTED PUSH-UPS",
    "muscles": [
      "chest",
      "triceps"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "WIDE GRIP PULL UP",
    "label": "WIDE GRIP PULL UP",
    "muscles": [
      "back",
      "shoulders",
      "biceps"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "WIDE PULL UP",
    "label": "WIDE PULL UP",
    "muscles": [
      "back"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "WIDE-GRIP PULLDOWN",
    "label": "WIDE-GRIP PULLDOWN",
    "muscles": [
      "back",
      "shoulders",
      "biceps"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "WINDSHIELD WIPERS",
    "label": "WINDSHIELD WIPERS",
    "muscles": [
      "abs"
    ],
    "equipment": "machine",
    "aliases": []
  },
  {
    "id": "WRIST CURL, CABLE",
    "label": "WRIST CURL, CABLE",
    "muscles": [
      "biceps"
    ],
    "equipment": "cable",
    "aliases": []
  },
  {
    "id": "YOGA EXERCISE: COW-CAT",
    "label": "YOGA EXERCISE: COW-CAT",
    "muscles": [
      "shoulders",
      "back",
      "abs"
    ],
    "equipment": "bodyweight",
    "aliases": []
  },
  {
    "id": "YTWL EXERCISE",
    "label": "YTWL EXERCISE",
    "muscles": [
      "shoulders",
      "back"
    ],
    "equipment": "dumbbell",
    "aliases": []
  },
  {
    "id": "ZOTTMAN CURL",
    "label": "ZOTTMAN CURL",
    "muscles": [
      "biceps"
    ],
    "equipment": "dumbbell",
    "aliases": []
  }
]

// Backward-compat layer: every exercise gets a `muscle` field === muscles[0]
// so older consumers reading the singular field continue working.
const _withMuscle = (e) => ({ ...e, muscle: e.muscles[0] })
const _ALL = ALL_EXERCISES.map(_withMuscle)

const CANONICAL_EXERCISE = {
  "chest": "BENCH PRESS",
  "shoulders": "OVERHEAD PRESS",
  "back": "BARBELL ROW",
  "forearms": "WRIST CURL",
  "quads": "SQUAT",
  "hamstrings": "ROMANIAN DEADLIFT",
  "calves": "STANDING CALF RAISE",
  "biceps": "BARBELL CURL",
  "triceps": "SKULL CRUSHER",
  "glutes": "HIP THRUST",
  "abs": "PLANK"
}

export function exercisesByMuscle(muscleId) {
  return _ALL.filter(e => e.muscles.includes(muscleId))
}

export function canonicalExerciseFor(muscleId) {
  const target = CANONICAL_EXERCISE[muscleId]
  if (target) {
    const found = _ALL.find(e => e.id === target && e.muscles.includes(muscleId))
    if (found) return found.id
  }
  const list = exercisesByMuscle(muscleId)
  return list[0]?.id || null
}

export function searchExercises(muscleId, query) {
  const list = exercisesByMuscle(muscleId)
  if (!query) return list
  const q = query.trim().toLowerCase()
  return list.filter(e =>
    e.label.toLowerCase().includes(q) ||
    e.aliases.some(a => a.toLowerCase().includes(q))
  )
}
